import type { CctvCamera } from './types';

/**
 * OSIRIS — publicly broadcast webcams (GENERATED).
 *
 * Open data, in the plainest sense: every camera here is one its operator
 * publishes themselves, on their own site or their own channel. What the web
 * does not have is a catalogue of them, so these were gathered by reading a
 * public index of such cameras — a list of pages rather than of feeds, with no
 * coordinates and no stream URLs, across 383 different hosts. This file is
 * what is left after reading those pages, and only what OSIRIS can actually
 * show. Regenerate with scratch/scrape_public_webcams.js.
 *
 * The 26 Rijkswaterstaat motorway cameras that index also lists are skipped:
 * netherlands.ts already fetches those live from the RWS API.
 *
 * Four shapes come out of it:
 *
 *   HLS      — a Wowza platform shared by a family of Dutch webcam sites,
 *              where the playlist carries no token. streamlock.net sends
 *              Access-Control-Allow-Origin: *, so these play straight from the
 *              browser and need no proxy entry.
 *   YouTube  — the operator broadcasts on their own channel. The link is the
 *              channel's /live URL, never a video id: these run for months and
 *              come back under a new id after every restart, so the id is
 *              resolved per request by /api/cctv/resolve rather than baked.
 *   iframe   — a provider embed page that stands on its own.
 *   link     — external_url alone, which puts the viewer into the viewer's
 *              external state: a way through to the camera rather than a copy
 *              of it. Three things land here.
 *
 * The third of those is worth spelling out, because it is a decision and not a
 * limitation. Most of the Wowza family answer an ad-blocker by replacing the
 * camera with a notice: the advertising is what keeps them online, please
 * switch the blocker off. Replaying their playlist here does the very thing
 * that notice objects to — takes the picture and leaves the page, and the
 * advertising on it, unloaded. That those particular playlists carry no token
 * is an accident of how each site was set up, not permission. So they link out
 * too, and only the handful of sites that ask nothing of their visitors are
 * played in place. The other two are a Wowza token that expires inside twenty
 * minutes, and a Referer check the browser cannot satisfy from here.
 *
 * external_url always points at the operator who runs the camera.
 *
 * Coordinates were resolved via OpenStreetMap Nominatim, country-filtered, and
 * cached in scratch/public-webcams-places.json so regenerating does not ask
 * again. Dutch cameras are looked up on their caption first ("Sint
 * Servaasbrug, Maastricht") and fall back to the village. Cameras whose caption
 * names no fixed place — aggregator channels cycling through dozens of
 * locations — are left out rather than pinned somewhere they are not.
 */

export const NETHERLANDS_PUBLIC_WEBCAMS: CctvCamera[] = [
  // ── Netherlands (229) ──
  { id: 'pubcam-netherlands-aalsmeer-westeinderplassen', lat: 52.247777, lng: 4.730493, name: 'Westeinderplassen', city: 'Aalsmeer', country: 'Netherlands', external_url: 'https://webcam-aalsmeer.nl/pages/cameras/westeinderplassen.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-aalsmeer-windsurfclub-aalsmeer', lat: 52.266944, lng: 4.749338, name: 'Windsurfclub Aalsmeer', city: 'Aalsmeer', country: 'Netherlands', external_url: 'https://webcam-aalsmeer.nl/pages/cameras/surfeiland.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-akkrum-vanaf-hotel-goerres', lat: 53.050125, lng: 5.83623, name: 'Vanaf Hotel Goerres', city: 'Akkrum', country: 'Netherlands', stream_url: 'https://584b389d712f9.streamlock.net/live/akkrum.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-friesemeren.nl/pages/cameras/akkrum.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-alkmaar-highlands-bouwcam', lat: 52.600854, lng: 4.817099, name: 'Highlands Bouwcam', city: 'Alkmaar', country: 'Netherlands', external_url: 'https://bouw.live/highlands-alkmaar/', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-alkmaar-ijsbaan-de-meent', lat: 52.632985, lng: 4.713607, name: 'IJsbaan De Meent', city: 'Alkmaar', country: 'Netherlands', external_url: 'https://www.youtube.com/@demeent7646/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-alkmaar-kijk-in-het-egelhuisje', lat: 52.600854, lng: 4.817099, name: 'Kijk in het Egelhuisje', city: 'Alkmaar', country: 'Netherlands', external_url: 'https://www.youtube.com/@b-ry87/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-alkmaar-tennisclub-alkmaar', lat: 52.600854, lng: 4.817099, name: 'Tennisclub Alkmaar', city: 'Alkmaar', country: 'Netherlands', external_url: 'https://www.youtube.com/@tcalkmaar6845/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-almere-windsurfvereniging-almere-centraal', lat: 52.334776, lng: 5.206401, name: 'Windsurfvereniging Almere-Centraal', city: 'Almere', country: 'Netherlands', external_url: 'https://www.youtube.com/@windsurfverenigingalmerece2705/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-golfbaan-ameland', lat: 53.449791, lng: 5.651894, name: 'Golfbaan Ameland', city: 'Ameland', country: 'Netherlands', external_url: 'https://webcams-ameland.nl/pages/cameras/golfbaan.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-strandhotel-buren-aan-zee', lat: 53.459857, lng: 5.807075, name: 'Strandhotel Buren aan Zee', city: 'Ameland', country: 'Netherlands', stream_url: 'https://www.ipcamlive.com/player/player.php?alias=strandhotelburen&autoplay=1', stream_type: 'iframe', external_url: 'https://www.ipcamlive.com/strandhotelburen', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-veerhaven-nes', lat: 53.434384, lng: 5.77464, name: 'Veerhaven Nes', city: 'Ameland', country: 'Netherlands', external_url: 'https://webcams-ameland.nl/pages/cameras/nes-haven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-vliegveld-helispot', lat: 53.406347, lng: 5.74825, name: 'Vliegveld (helispot)', city: 'Ameland', country: 'Netherlands', external_url: 'https://webcams-ameland.nl/pages/cameras/vliegveld-helispot.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-vliegveld-overzicht', lat: 53.406347, lng: 5.74825, name: 'Vliegveld (overzicht)', city: 'Ameland', country: 'Netherlands', external_url: 'https://webcams-ameland.nl/pages/cameras/vliegveld-overzicht.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-waddenhaven-nes', lat: 53.437492, lng: 5.775524, name: 'Waddenhaven Nes', city: 'Ameland', country: 'Netherlands', external_url: 'https://webcams-ameland.nl/pages/cameras/waddenhaven-nes.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-wagenborg-terminal-nes', lat: 53.406347, lng: 5.74825, name: 'Wagenborg Terminal Nes', city: 'Ameland', country: 'Netherlands', external_url: 'https://www.youtube.com/@wagenborgpassagiersdienste5155/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ameland-webcams-vvv-ameland', lat: 53.406347, lng: 5.74825, name: 'Webcams VVV-Ameland', city: 'Ameland', country: 'Netherlands', external_url: 'https://www.youtube.com/@VVVAmeland/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-amersfoort-dierenpark-amersfoort', lat: 52.149526, lng: 5.344989, name: 'Dierenpark Amersfoort', city: 'Amersfoort', country: 'Netherlands', external_url: 'https://www.youtube.com/@dpamersfoort/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-amersfoort-spoorzicht-met-mo-railcam', lat: 52.16377, lng: 5.408885, name: 'Spoorzicht met Mo (Railcam)', city: 'Amersfoort', country: 'Netherlands', external_url: 'https://www.youtube.com/@Mo_online/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-amsterdam-bio-ij-cam', lat: 52.37308, lng: 4.892453, name: 'BIO IJ-cam', city: 'Amsterdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@BiO_NL/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-amsterdam-bouwcam-zuidasdok', lat: 52.37308, lng: 4.892453, name: 'Bouwcam Zuidasdok', city: 'Amsterdam', country: 'Netherlands', external_url: 'https://bouw.live/zuidasdok-amsterdam/', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-amsterdam-de-dam', lat: 52.373145, lng: 4.891336, name: 'De Dam', city: 'Amsterdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@Now4Rent/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-amsterdam-holocaust-namenmonument-nederland', lat: 52.365706, lng: 4.904975, name: 'Holocaust Namenmonument Nederland', city: 'Amsterdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@holocaustnamenmonumentnede7728/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-amsterdam-ij-vanaf-movenpick-hotel', lat: 52.37308, lng: 4.892453, name: 'IJ vanaf Mövenpick Hotel', city: 'Amsterdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@moevenpickamsterdam/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-andijk-webcam-pwn', lat: 52.746734, lng: 5.221793, name: 'Webcam PWN', city: 'Andijk', country: 'Netherlands', external_url: 'https://bouw.live/pwn-andijk/', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-apeldoorn-peregrine-falcon-nl', lat: 52.179574, lng: 5.930078, name: 'Peregrine Falcon NL', city: 'Apeldoorn', country: 'Netherlands', external_url: 'https://www.youtube.com/@PeregrineFalconNL/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-arnhem-slechtvalken-eusebiuskerk', lat: 51.984257, lng: 5.910857, name: 'Slechtvalken Eusebiuskerk', city: 'Arnhem', country: 'Netherlands', external_url: 'https://www.youtube.com/@Eusebius_Arnhem/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-barneveld-volvo-klassiekers', lat: 52.171507, lng: 5.645439, name: 'Volvo Klassiekers', city: 'Barneveld', country: 'Netherlands', external_url: 'https://www.youtube.com/@VolvoKlassiekers/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-blokzijl-zicht-op-de-sluis', lat: 52.726149, lng: 5.961419, name: 'Zicht op de sluis', city: 'Blokzijl', country: 'Netherlands', external_url: 'https://webcam-blokzijl.nl/pages/cameras/sluis.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-broek-op-langedijk-oosterdelgebied-veldzorg', lat: 52.675121, lng: 4.803109, name: 'Oosterdelgebied (Veldzorg)', city: 'Broek op Langedijk', country: 'Netherlands', stream_url: 'https://www.ipcamlive.com/player/player.php?alias=veldzorg&autoplay=1', stream_type: 'iframe', external_url: 'https://www.ipcamlive.com/veldzorg', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-brouwersdam-pixlife-test-camera', lat: 52.311517, lng: 4.638276, name: 'PixLife (Test camera)', city: 'Brouwersdam', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=KjK02QIm4ZI', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-brouwersdam-webcam-pooltje', lat: 52.311517, lng: 4.638276, name: 'Webcam Pooltje', city: 'Brouwersdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@brouwersdamcam321/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-cadzand-bad-beachcam-en-surfspots', lat: 51.377181, lng: 3.388391, name: 'Beachcam en Surfspots', city: 'Cadzand-Bad', country: 'Netherlands', external_url: 'https://live.netcamviewer.nl/beachcam-cadzand/1069', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-capelle-aan-den-ijssel-abram-van-rijckevorselweg', lat: 51.925993, lng: 4.570051, name: 'Abram van Rijckevorselweg', city: 'Capelle aan den IJssel', country: 'Netherlands', external_url: 'https://www.youtube.com/@AxisExperienceCenterTheNetherl/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-castricum-strandpaviljoen-zeezicht', lat: 52.549674, lng: 4.669619, name: 'Strandpaviljoen Zeezicht', city: 'Castricum', country: 'Netherlands', external_url: 'https://www.youtube.com/@Livestreamaanzee/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-dalfsen-modelvliegclub-friendship', lat: 52.511784, lng: 6.256637, name: 'Modelvliegclub Friendship', city: 'Dalfsen', country: 'Netherlands', external_url: 'https://www.youtube.com/@BennyBreman/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-de-mortel-hans-natuurkanaal', lat: 51.540329, lng: 5.708906, name: 'Hans Natuurkanaal', city: 'De Mortel', country: 'Netherlands', external_url: 'https://www.youtube.com/@hansnatuurkanaal/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-delfzijl-eems-noord', lat: 53.332564, lng: 6.913514, name: 'Eems (Noord)', city: 'Delfzijl', country: 'Netherlands', external_url: 'https://webcam-delfzijl.nl/pages/cameras/eems-noord.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-delfzijl-eems-zuid', lat: 53.332564, lng: 6.913514, name: 'Eems (Zuid)', city: 'Delfzijl', country: 'Netherlands', external_url: 'https://webcam-delfzijl.nl/pages/cameras/eems-zuid.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-delfzijl-haven', lat: 53.331908, lng: 6.92943, name: 'Haven', city: 'Delfzijl', country: 'Netherlands', external_url: 'https://webcam-delfzijl.nl/pages/cameras/haven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-delfzijl-vanaf-flat-hoogwatum', lat: 53.332564, lng: 6.913514, name: 'Vanaf Flat Hoogwatum', city: 'Delfzijl', country: 'Netherlands', external_url: 'https://webcam-delfzijl.nl/pages/cameras/hoogwatum.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-den-haag-voetbal-en-cricketvereniging-quick', lat: 52.079984, lng: 4.311346, name: 'Voetbal- en Cricketvereniging Quick', city: 'Den Haag', country: 'Netherlands', external_url: 'https://www.youtube.com/@hv_cvquick/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-den-haag-vreugdevuur-duindorp', lat: 52.079984, lng: 4.311346, name: 'Vreugdevuur Duindorp', city: 'Den Haag', country: 'Netherlands', external_url: 'https://www.youtube.com/@duindorpvreugdevuurnl/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-den-helder-airport-helihaven', lat: 52.957976, lng: 4.760279, name: 'Airport (Helihaven)', city: 'Den Helder', country: 'Netherlands', external_url: 'https://webcam-denhelder.nl/pages/cameras/dh-airport.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-domburg-strandpaviljoen-oase', lat: 51.563214, lng: 3.496728, name: 'Strandpaviljoen Oase', city: 'Domburg', country: 'Netherlands', external_url: 'https://www.youtube.com/@OaseDomburg-ry5ct/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-dongen-ijsbaan-en-meer', lat: 51.642893, lng: 4.957877, name: 'IJsbaan en meer', city: 'Dongen', country: 'Netherlands', external_url: 'https://www.youtube.com/@DongenWebcam/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-dordrecht-drierivierenpunt', lat: 51.768955, lng: 4.686789, name: 'Drierivierenpunt', city: 'Dordrecht', country: 'Netherlands', external_url: 'https://www.youtube.com/@wvthoog/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-dordrecht-weercam-dordrechtnu', lat: 51.768955, lng: 4.686789, name: 'Weercam DordrechtNu', city: 'Dordrecht', country: 'Netherlands', external_url: 'https://www.youtube.com/@DordrechtNu/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-eernewoude-bij-hotel-princenhof', lat: 53.132235, lng: 5.940653, name: 'Bij Hotel Princenhof', city: 'Eernewoude', country: 'Netherlands', stream_url: 'https://5b8d2cbe62ad6.streamlock.net/live/eernewoude.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-friesemeren.nl/pages/cameras/eernewoude.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-egmond-aan-zee-pompplein', lat: 52.61753, lng: 4.622114, name: 'Pompplein', city: 'Egmond aan Zee', country: 'Netherlands', external_url: 'https://www.youtube.com/@egmondaanzee/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-elburg-jufferenstraat-museum-elburg', lat: 52.447702, lng: 5.835504, name: 'Jufferenstraat (Museum Elburg)', city: 'Elburg', country: 'Netherlands', external_url: 'https://www.youtube.com/@gemeente_elburg/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-elburg-vischmarkt', lat: 52.448474, lng: 5.833834, name: 'Vischmarkt', city: 'Elburg', country: 'Netherlands', external_url: 'https://www.youtube.com/@LocoMediaGroep/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-enkhuizen-oude-haven', lat: 52.701811, lng: 5.290932, name: 'Oude Haven', city: 'Enkhuizen', country: 'Netherlands', external_url: 'https://webcam-enkhuizen.nl/pages/cameras/oude-haven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-enkhuizen-zuiderzee-museum', lat: 52.75772, lng: 5.320694, name: 'Zuiderzee Museum', city: 'Enkhuizen', country: 'Netherlands', external_url: 'https://webcam-enkhuizen.nl/pages/cameras/zuiderzee.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-gemert-vogelwerkgroep-slechtvalk', lat: 51.558983, lng: 5.686459, name: 'Vogelwerkgroep (Slechtvalk)', city: 'Gemert', country: 'Netherlands', external_url: 'https://www.youtube.com/@VogelwerkgroepGemert/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-genemuiden-zicht-op-genemuiden', lat: 52.622883, lng: 6.042431, name: 'Zicht op Genemuiden', city: 'Genemuiden', country: 'Netherlands', external_url: 'https://www.youtube.com/@BennyBreman/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-groede-strandcamping-groede', lat: 51.394355, lng: 3.487611, name: 'Strandcamping Groede', city: 'Groede', country: 'Netherlands', external_url: 'https://www.youtube.com/@StrandcampingGroede/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-groningen-gasunie-slechtvalk-webcam', lat: 53.219065, lng: 6.568008, name: 'Gasunie Slechtvalk webcam', city: 'Groningen', country: 'Netherlands', external_url: 'https://www.youtube.com/@GasunieSlechtvalk/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-groningen-stationsweg-groninger-museum', lat: 53.219065, lng: 6.568008, name: 'Stationsweg/Groninger Museum', city: 'Groningen', country: 'Netherlands', external_url: 'https://www.youtube.com/@Bouwwebcam/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-groningen-vismarkt', lat: 53.217221, lng: 6.564877, name: 'Vismarkt', city: 'Groningen', country: 'Netherlands', external_url: 'https://www.youtube.com/@VismarktGroningenWebcam/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-haaksbergen-ijschclub-haaksbergen', lat: 52.156458, lng: 6.740239, name: 'IJschclub Haaksbergen', city: 'Haaksbergen', country: 'Netherlands', external_url: 'https://www.youtube.com/@ijschclubhaaksbergen4445/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-afvaloven', lat: 53.17521, lng: 5.4142, name: 'Afvaloven', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/afvaloven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-binnenhaven', lat: 53.17521, lng: 5.4142, name: 'Binnenhaven', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/binnenhaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-havenmond', lat: 53.176554, lng: 5.403349, name: 'Havenmond', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/havenmond2.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-havenmond-draaibare-camera', lat: 53.17521, lng: 5.4142, name: 'Havenmond (draaibare camera)', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/havenmond.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-noorderhaven', lat: 53.021793, lng: 5.204951, name: 'Noorderhaven', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/noorderhaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-noorderpier', lat: 53.182719, lng: 5.414051, name: 'Noorderpier', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/noorderpier.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-strand', lat: 53.17521, lng: 5.4142, name: 'Strand', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/strand.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-tjerk-hiddessluis', lat: 53.17521, lng: 5.4142, name: 'Tjerk Hiddessluis', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/th-sluis.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-vanaf-de-kerktoren', lat: 53.17521, lng: 5.4142, name: 'Vanaf de Kerktoren', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/kerktoren.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-vissershaven', lat: 53.181374, lng: 5.416621, name: 'Vissershaven', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/vissershaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-willemshaven', lat: 53.171564, lng: 5.41068, name: 'Willemshaven', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/willemshaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-willemshaven-cam-2', lat: 53.17521, lng: 5.4142, name: 'Willemshaven (Cam 2)', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/willemshaven2.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-windmolen-webcam', lat: 53.17521, lng: 5.4142, name: 'Windmolen webcam', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/windmolen.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-z-o-singel', lat: 53.17521, lng: 5.4142, name: 'Z.O. Singel', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/zo-singel.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-harlingen-zuiderpier', lat: 53.171844, lng: 5.408823, name: 'Zuiderpier', city: 'Harlingen', country: 'Netherlands', external_url: 'https://webcam-harlingen.nl/pages/cameras/zuiderpier.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hengelo-natuurgebied-kristalbad', lat: 52.252319, lng: 6.795526, name: 'Natuurgebied Kristalbad', city: 'Hengelo', country: 'Netherlands', external_url: 'https://live.netcamviewer.nl/Webcam-Waterschap-Vechtstromen/854', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-herwijnen-ooievaars-tv-buitengewoon', lat: 51.826723, lng: 5.12968, name: 'Ooievaars (TV Buitengewoon)', city: 'Herwijnen', country: 'Netherlands', external_url: 'https://www.youtube.com/@tvbuitengewoon/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hilversum-bouwcam-bij-station-ns', lat: 52.224137, lng: 5.17194, name: 'Bouwcam bij Station NS', city: 'Hilversum', country: 'Netherlands', external_url: 'https://bouw.live/stationshart-hilversum/', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hilversum-vliegveld', lat: 52.191154, lng: 5.145925, name: 'Vliegveld', city: 'Hilversum', country: 'Netherlands', external_url: 'https://webcam-airport.nl/pages/cameras/hilversum.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hoek-van-holland-berghaven', lat: 51.976359, lng: 4.124379, name: 'Berghaven', city: 'Hoek van Holland', country: 'Netherlands', external_url: 'https://webcam-hoekvanholland.nl/pages/cameras/berghaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hoek-van-holland-hoekse-watersportvereniging', lat: 51.977162, lng: 4.131453, name: 'Hoekse Watersportvereniging', city: 'Hoek van Holland', country: 'Netherlands', external_url: 'https://webcam-hoekvanholland.nl/pages/cameras/strand.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hoek-van-holland-monding-nieuwe-waterweg', lat: 51.977162, lng: 4.131453, name: 'Monding Nieuwe Waterweg', city: 'Hoek van Holland', country: 'Netherlands', external_url: 'https://webcam-hoekvanholland.nl/pages/cameras/waterweg-ingang.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hoek-van-holland-nieuwe-waterweg', lat: 51.971745, lng: 4.128577, name: 'Nieuwe Waterweg', city: 'Hoek van Holland', country: 'Netherlands', external_url: 'https://www.youtube.com/@port-of-rotterdam/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hoek-van-holland-nieuwe-waterweg-draaibaar', lat: 51.977162, lng: 4.131453, name: 'Nieuwe Waterweg (draaibaar)', city: 'Hoek van Holland', country: 'Netherlands', external_url: 'https://webcam-hoekvanholland.nl/pages/cameras/waterweg-hvh.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hoogeveen-vliegveld-oost', lat: 52.726426, lng: 6.493081, name: 'Vliegveld (Oost)', city: 'Hoogeveen', country: 'Netherlands', external_url: 'https://webcam-airport.nl/pages/cameras/hoogeveen-oost.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-hoogeveen-vliegveld-west', lat: 52.726426, lng: 6.493081, name: 'Vliegveld (West)', city: 'Hoogeveen', country: 'Netherlands', external_url: 'https://webcam-airport.nl/pages/cameras/hoogeveen-west.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-huissen-marktplein', lat: 51.93835, lng: 5.939377, name: 'Marktplein', city: 'Huissen', country: 'Netherlands', external_url: 'https://www.youtube.com/@omroeplw/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ijmuiden-tata-steel-via-frisse-wind-nu', lat: 52.457414, lng: 4.611621, name: 'Tata Steel via Frisse Wind Nu', city: 'IJmuiden', country: 'Netherlands', external_url: 'https://www.youtube.com/@frissewindnu/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ijmuiden-tennisvereniging-heerenduinen', lat: 52.457414, lng: 4.611621, name: 'Tennisvereniging Heerenduinen', city: 'IJmuiden', country: 'Netherlands', external_url: 'https://www.youtube.com/@Heerenduinen/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ijmuiden-webcam-kvsa-shipm8-com', lat: 52.457414, lng: 4.611621, name: 'Webcam KVSA & SHIPM8.com', city: 'IJmuiden', country: 'Netherlands', external_url: 'https://www.youtube.com/@shipm8/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ijsselstein-kerstboom-gerbrandytoren', lat: 52.024638, lng: 5.045879, name: 'Kerstboom Gerbrandytoren', city: 'IJsselstein', country: 'Netherlands', external_url: 'https://www.youtube.com/@livechristmastree/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ijsselstein-ooievaarsnest', lat: 52.024638, lng: 5.045879, name: 'Ooievaarsnest', city: 'IJsselstein', country: 'Netherlands', external_url: 'https://www.youtube.com/@terbergtotaalinstallaties8183/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-julianadorp-ijsclub', lat: 52.892318, lng: 4.755502, name: 'IJsclub', city: 'Julianadorp', country: 'Netherlands', external_url: 'https://www.youtube.com/@ijsclubjulianadorp421/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-kampen-skyline', lat: 52.555948, lng: 5.90333, name: 'Skyline', city: 'Kampen', country: 'Netherlands', stream_url: 'https://584b389d712f9.streamlock.net/live/kampen.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-kampen.nl/pages/cameras/skyline.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-kampen-stadsbrug', lat: 52.559566, lng: 5.918869, name: 'Stadsbrug', city: 'Kampen', country: 'Netherlands', stream_url: 'https://584b389d712f9.streamlock.net/live/kampen2.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-kampen.nl/pages/cameras/stadsbrug.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-katwijk-aan-zee-bed-and-breakfast-aan-strand', lat: 52.204898, lng: 4.396598, name: 'Bed and Breakfast Aan Strand', city: 'Katwijk aan Zee', country: 'Netherlands', external_url: 'https://www.youtube.com/@aan-strand/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-kerkrade-gaia-zoo-livestream', lat: 50.874909, lng: 6.059385, name: 'Gaia Zoo Livestream', city: 'Kerkrade', country: 'Netherlands', external_url: 'https://www.youtube.com/@GaiaZOO/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-koewacht-alpaca-world', lat: 51.228982, lng: 3.970228, name: 'Alpaca World', city: 'Koewacht', country: 'Netherlands', external_url: 'https://www.youtube.com/@Alpaca-World/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-kootwijkerbroek-imkerij-de-valksche-bijenhof', lat: 52.151351, lng: 5.66315, name: 'Imkerij De Valksche Bijenhof', city: 'Kootwijkerbroek', country: 'Netherlands', external_url: 'https://www.youtube.com/@honingonline-NL/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-lauwersoog-w-e-c-zeehondencentrum', lat: 53.403633, lng: 6.214238, name: 'W.E.C. Zeehondencentrum', city: 'Lauwersoog', country: 'Netherlands', external_url: 'https://www.youtube.com/@zeehondencentrumpieterburen/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-leeuwarden-de-oldehove-toren', lat: 53.200594, lng: 5.791855, name: 'De Oldehove Toren', city: 'Leeuwarden', country: 'Netherlands', external_url: 'https://www.youtube.com/@TresoarBoterhoek1/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-leeuwarden-wilhelminaplein', lat: 53.199534, lng: 5.794063, name: 'Wilhelminaplein', city: 'Leeuwarden', country: 'Netherlands', external_url: 'https://www.youtube.com/@Webcamsinbeeld/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-leeuwarden-ljouwert-11-stedenhal', lat: 53.200594, lng: 5.791855, name: '11 Stedenhal', city: 'Leeuwarden (Ljouwert)', country: 'Netherlands', external_url: 'https://webcam-leeuwarden.nl/pages/cameras/11stedenhal.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-leiden-onder-water', lat: 52.159475, lng: 4.490884, name: 'Onder water', city: 'Leiden', country: 'Netherlands', external_url: 'https://www.youtube.com/@CanalCamLeiden/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-lelystad-marina-lelystad-haven', lat: 52.502566, lng: 5.41283, name: 'Marina Lelystad Haven', city: 'Lelystad', country: 'Netherlands', external_url: 'https://webcam-lelystad.nl/pages/cameras/haven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-lelystad-marina-lelystad-havenmond', lat: 52.515095, lng: 5.476891, name: 'Marina Lelystad Havenmond', city: 'Lelystad', country: 'Netherlands', external_url: 'https://webcam-lelystad.nl/pages/cameras/havenmond.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-lemmer-rondkijken-lemmer-e-o', lat: 52.844486, lng: 5.709914, name: 'Rondkijken Lemmer e.o.', city: 'Lemmer', country: 'Netherlands', external_url: 'https://www.youtube.com/@webcamlemmer4841/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-loosdrecht-de-heeren-van-loosdrecht', lat: 52.202599, lng: 5.090563, name: 'De Heeren van Loosdrecht', city: 'Loosdrecht', country: 'Netherlands', external_url: 'https://www.youtube.com/@heerenvanloosdrecht207/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-loosdrecht-watersport-vereniging-de-vrijbuiter', lat: 52.202599, lng: 5.090563, name: 'Watersport Vereniging De Vrijbuiter', city: 'Loosdrecht', country: 'Netherlands', external_url: 'https://www.youtube.com/@GWVdeVrijbuiter/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-maassluis-zeesleper-elbe', lat: 51.926667, lng: 4.244001, name: 'Zeesleper Elbe', city: 'Maassluis', country: 'Netherlands', external_url: 'https://www.youtube.com/@zeesleper-elbe/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-maastricht-andr-233-rieu-vrijthof', lat: 50.851244, lng: 5.690977, name: 'Andr&#233 Rieu - Vrijthof', city: 'Maastricht', country: 'Netherlands', external_url: 'https://www.youtube.com/@andrerieu/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-maastricht-sint-servaasbrug', lat: 50.849411, lng: 5.69572, name: 'Sint Servaasbrug', city: 'Maastricht', country: 'Netherlands', stream_url: 'https://565c3c746b763.streamlock.net/live/maastricht.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-maastricht.nl/pages/cameras/servaasbrug.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-maastricht-vrijthof', lat: 50.849073, lng: 5.68863, name: 'Vrijthof', city: 'Maastricht', country: 'Netherlands', stream_url: 'https://565c3c746b763.streamlock.net/live/maastricht2.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-maastricht.nl/pages/cameras/vrijthof.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-markelo-han-bouwmeester-natuurfotografie', lat: 52.234714, lng: 6.494985, name: 'Han Bouwmeester Natuurfotografie', city: 'Markelo', country: 'Netherlands', external_url: 'https://www.youtube.com/@Enjoywildlife/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-meteren-werk-zuidwestboog-prorail', lat: 51.863721, lng: 5.283424, name: 'Werk Zuidwestboog (ProRail)', city: 'Meteren', country: 'Netherlands', external_url: 'https://www.youtube.com/@prorail/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-middelburg-station-piet-voscam', lat: 51.499678, lng: 3.613737, name: 'Station (Piet Voscam)', city: 'Middelburg', country: 'Netherlands', external_url: 'https://www.youtube.com/@fayard-mdb/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-middenmeer-vliegveld-cam-1', lat: 52.811147, lng: 4.994846, name: 'Vliegveld (Cam 1)', city: 'Middenmeer', country: 'Netherlands', external_url: 'https://webcam-airport.nl/pages/cameras/middenmeer.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-middenmeer-vliegveld-cam-2', lat: 52.811147, lng: 4.994846, name: 'Vliegveld (Cam 2)', city: 'Middenmeer', country: 'Netherlands', external_url: 'https://webcam-airport.nl/pages/cameras/middenmeer-draaibaar.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-mierlo-hout-rail-cam-nl', lat: 51.467067, lng: 5.634656, name: 'Rail Cam NL', city: 'Mierlo-Hout', country: 'Netherlands', external_url: 'https://www.youtube.com/@MarioRailcamNL/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-monnickendam-gouwzee', lat: 52.469147, lng: 5.085135, name: 'Gouwzee', city: 'Monnickendam', country: 'Netherlands', external_url: 'https://webcam-monnickendam.nl/pages/cameras/gouwzee.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-monnickendam-jachthaven', lat: 52.463562, lng: 5.035737, name: 'Jachthaven', city: 'Monnickendam', country: 'Netherlands', external_url: 'https://webcam-monnickendam.nl/pages/cameras/jachthaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-nieuwegein-down-under-recreatie', lat: 52.036715, lng: 5.083612, name: 'Down Under Recreatie', city: 'Nieuwegein', country: 'Netherlands', stream_url: 'https://rtsp.me/embed/eY9ftGB2', stream_type: 'iframe', external_url: 'https://rtsp.me/embed/eY9ftGB2', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-oosterhout-ijsmarkt-oosterhout', lat: 51.632238, lng: 4.863042, name: 'IJsmarkt Oosterhout', city: 'Oosterhout', country: 'Netherlands', external_url: 'https://www.youtube.com/@VDS-LIVE/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-oostkapelle-overzicht-vanaf-de-kerk-1', lat: 51.565452, lng: 3.550904, name: 'Overzicht vanaf de Kerk (1)', city: 'Oostkapelle', country: 'Netherlands', external_url: 'https://www.youtube.com/@ondernemersnatuurlijkoostk4512/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-oostkapelle-overzicht-vanaf-de-kerk-2', lat: 51.565452, lng: 3.550904, name: 'Overzicht vanaf de Kerk (2)', city: 'Oostkapelle', country: 'Netherlands', external_url: 'https://www.youtube.com/@ondernemersnatuurlijkeoost5965/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-otterloo-hoge-veluwe-wildcamera', lat: 52.368139, lng: 5.179099, name: 'Hoge Veluwe wildcamera', city: 'Otterloo', country: 'Netherlands', external_url: 'https://www.youtube.com/@hogeveluwe/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-oude-schouw-vanaf-restaurant-de-oude-schouw', lat: 53.065016, lng: 5.809825, name: 'Vanaf Restaurant De Oude Schouw', city: 'Oude Schouw', country: 'Netherlands', stream_url: 'https://6162417352ffd.streamlock.net/live/oudeschouw.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-friesemeren.nl/pages/cameras/oude-schouw.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-oudega-de-wijde-ee', lat: 52.992127, lng: 5.552868, name: 'De Wijde EE', city: 'Oudega', country: 'Netherlands', stream_url: 'https://6162417352ffd.streamlock.net/live/iesicht.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-friesemeren.nl/pages/cameras/wijde-ee.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-petten-strand-bij-reddingsbrigade-petten', lat: 52.768597, lng: 4.662609, name: 'Strand bij Reddingsbrigade Petten', city: 'Petten', country: 'Netherlands', external_url: 'https://www.youtube.com/@reddingsbrigadepetten148/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-purmerend-milieustraat-purmerend', lat: 52.502479, lng: 4.961483, name: 'Milieustraat Purmerend', city: 'Purmerend', country: 'Netherlands', external_url: 'https://www.youtube.com/@GemeentePurmerend0299/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-raalte-raalte-on-ice', lat: 52.387433, lng: 6.307848, name: 'Raalte on Ice', city: 'Raalte', country: 'Netherlands', external_url: 'https://www.youtube.com/@beekmanraalte1221/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-reeuwijk-windsurf-club-reeuwijk', lat: 52.056646, lng: 4.739748, name: 'Windsurf Club Reeuwijk', city: 'Reeuwijk', country: 'Netherlands', external_url: 'https://www.youtube.com/@wscr/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-renesse-camping-duinhoeve', lat: 51.739661, lng: 3.778939, name: 'Camping Duinhoeve', city: 'Renesse', country: 'Netherlands', external_url: 'https://www.youtube.com/@campingduinhoeverenesse6838/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-rheden-knooppunt-velperbroek', lat: 51.983111, lng: 5.980089, name: 'Knooppunt Velperbroek', city: 'Rheden', country: 'Netherlands', external_url: 'https://www.youtube.com/@studiorhedenonline/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-ridderkerk-scheepvaart-op-de-nieuwe-maas', lat: 51.870991, lng: 4.592648, name: 'Scheepvaart op de Nieuwe Maas', city: 'Ridderkerk', country: 'Netherlands', external_url: 'https://webcam-rotterdam.nl/pages/cameras/ridderkerk.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-roermond-toren7-webcam-vanaf-de-eci', lat: 51.19339, lng: 5.988265, name: 'Toren7 Webcam vanaf de ECI', city: 'Roermond', country: 'Netherlands', external_url: 'https://www.youtube.com/@toren7roermond-tvtoren647/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-roermond-webcam-toren-7', lat: 51.19339, lng: 5.988265, name: 'Webcam Toren 7', city: 'Roermond', country: 'Netherlands', external_url: 'https://www.youtube.com/@Toren7-IT/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-rotterdam-bij-hal-4', lat: 51.924442, lng: 4.47775, name: 'Bij HAL 4', city: 'Rotterdam', country: 'Netherlands', external_url: 'https://webcam-rotterdam.nl/pages/cameras/hal4.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-rotterdam-hotel-chicago-bouwcam', lat: 51.924442, lng: 4.47775, name: 'Hotel Chicago (Bouwcam)', city: 'Rotterdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@westcordvideo/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-rotterdam-kpn-led-wall-erasmusbrug', lat: 51.924442, lng: 4.47775, name: 'KPN LED-wall / Erasmusbrug', city: 'Rotterdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@RotterdamMakeItHappen/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-rotterdam-ontwikkeling-rijnhaven', lat: 51.924442, lng: 4.47775, name: 'Ontwikkeling Rijnhaven', city: 'Rotterdam', country: 'Netherlands', external_url: 'https://www.youtube.com/@GemeenteRotterdam/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-rotterdam-terras-hotel-new-york', lat: 51.924442, lng: 4.47775, name: 'Terras Hotel New York', city: 'Rotterdam', country: 'Netherlands', external_url: 'https://webcam-rotterdam.nl/pages/cameras/hotel-new-york.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-rotterdam-van-brienenoordbrug-de-kuip', lat: 51.924442, lng: 4.47775, name: 'Van Brienenoordbrug / De Kuip', city: 'Rotterdam', country: 'Netherlands', external_url: 'https://webcam-rotterdam.nl/pages/cameras/de-esch.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-scheveningen-strandpaviljoen-aloha-surf-and-food', lat: 52.106745, lng: 4.273694, name: 'Strandpaviljoen Aloha Surf and Food', city: 'Scheveningen', country: 'Netherlands', external_url: 'https://www.youtube.com/@AlohaSurf/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-schiphol-joe-adam-planespotting', lat: 52.308039, lng: 4.762198, name: 'Joe Adam Planespotting', city: 'Schiphol', country: 'Netherlands', external_url: 'https://www.youtube.com/@JoeAdamChannel/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-schiphol-planespotting-ams-live', lat: 52.308039, lng: 4.762198, name: 'Planespotting AMS Live', city: 'Schiphol', country: 'Netherlands', external_url: 'https://www.youtube.com/@AMSLIVE/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-sneek-terrassen-marktstraat', lat: 53.033548, lng: 5.661103, name: 'Terrassen Marktstraat', city: 'Sneek', country: 'Netherlands', external_url: 'https://www.youtube.com/@sneekismeer2914/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-stadskanaal-vliegveld', lat: 52.996705, lng: 7.022665, name: 'Vliegveld', city: 'Stadskanaal', country: 'Netherlands', external_url: 'https://webcam-airport.nl/pages/cameras/stadskanaal.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-steenwijk-de-markt-reuzenrad', lat: 52.78955, lng: 6.121048, name: 'De Markt (reuzenrad)', city: 'Steenwijk', country: 'Netherlands', external_url: 'https://www.youtube.com/@SteenwijkerlandTV/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terherne-jachthaven', lat: 53.045489, lng: 5.783684, name: 'Jachthaven', city: 'Terherne', country: 'Netherlands', stream_url: 'https://6162417352ffd.streamlock.net/live/terherne.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-friesemeren.nl/pages/cameras/terherne.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terneuzen-vanaf-brasserie-westbeer-oost', lat: 51.298843, lng: 3.842204, name: 'Vanaf Brasserie Westbeer (Oost)', city: 'Terneuzen', country: 'Netherlands', external_url: 'https://webcam-terneuzen.nl/pages/cameras/oost.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terneuzen-vanaf-brasserie-westbeer-west', lat: 51.298843, lng: 3.842204, name: 'Vanaf Brasserie Westbeer (West)', city: 'Terneuzen', country: 'Netherlands', external_url: 'https://webcam-terneuzen.nl/pages/cameras/west.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terschelling-brandarisplein-hotel-nap', lat: 53.333906, lng: 5.351491, name: 'Brandarisplein Hotel NAP', city: 'Terschelling', country: 'Netherlands', external_url: 'https://webcam-brandaris.nl/pages/cameras/hotel-nap.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terschelling-haven', lat: 53.357741, lng: 5.216581, name: 'Haven', city: 'Terschelling', country: 'Netherlands', external_url: 'https://webcam-brandaris.nl/pages/cameras/jachthaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terschelling-haven-bij-vvv-kantoor', lat: 53.333906, lng: 5.351491, name: 'Haven bij VVV kantoor', city: 'Terschelling', country: 'Netherlands', external_url: 'https://webcam-brandaris.nl/pages/cameras/vvv-terschelling.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terschelling-havenkom', lat: 53.333906, lng: 5.351491, name: 'Havenkom', city: 'Terschelling', country: 'Netherlands', external_url: 'https://webcam-brandaris.nl/pages/cameras/havenkom.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terschelling-havenplein-en-veerkade', lat: 53.333906, lng: 5.351491, name: 'Havenplein en Veerkade', city: 'Terschelling', country: 'Netherlands', external_url: 'https://webcam-brandaris.nl/pages/cameras/veerkade.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terschelling-vanaf-hotel-schylge-oost', lat: 53.333906, lng: 5.351491, name: 'Vanaf Hotel Schylge (Oost)', city: 'Terschelling', country: 'Netherlands', external_url: 'https://webcam-brandaris.nl/pages/cameras/hotel-schylge-oost.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terschelling-vanaf-hotel-schylge-west', lat: 53.333906, lng: 5.351491, name: 'Vanaf Hotel Schylge (West)', city: 'Terschelling', country: 'Netherlands', external_url: 'https://webcam-brandaris.nl/pages/cameras/hotel-schylge-west.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-terwolde-bosgoed-animal-paradise', lat: 52.281687, lng: 6.099803, name: 'Bosgoed Animal Paradise', city: 'Terwolde', country: 'Netherlands', external_url: 'https://www.youtube.com/@mauritsbosgoed/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-teuge-vliegveld', lat: 52.242407, lng: 6.050696, name: 'Vliegveld', city: 'Teuge', country: 'Netherlands', external_url: 'https://webcam-airport.nl/pages/cameras/teuge.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-bij-surfschool-foamball', lat: 53.076785, lng: 4.905757, name: 'Bij Surfschool Foamball', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/surfschool-foamball.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-de-koog-dikke-zeehond', lat: 53.076785, lng: 4.905757, name: 'De Koog - Dikke Zeehond', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=f_CtUNq1FR0', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-dierenopvang-woody-s', lat: 53.076785, lng: 4.905757, name: 'Dierenopvang Woody\'s', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=NF6DzpvWWUU', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-golfbaan-de-texelse', lat: 53.150889, lng: 4.849747, name: 'Golfbaan de Texelse', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/golfbaan.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-haven-van-oudeschild', lat: 53.076785, lng: 4.905757, name: 'Haven van Oudeschild', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=NYGtSbvt6d0', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-havenmond-oudeschild', lat: 53.076785, lng: 4.905757, name: 'Havenmond Oudeschild', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/havenmond-oudeschild.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-kattenopvang-woody-s', lat: 53.076785, lng: 4.905757, name: 'Kattenopvang Woody\'s', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=lpp-rJg0uAg', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-kerkje-van-den-hoorn', lat: 53.076785, lng: 4.905757, name: 'Kerkje van Den Hoorn', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/den-hoorn.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-lammetjes-cam', lat: 53.076785, lng: 4.905757, name: 'Lammetjes cam', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/lammetjes-cam.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-landschap-de-hoge-berg', lat: 53.076785, lng: 4.905757, name: 'Landschap De Hoge Berg', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/@Texelinformatie/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-natuur-waal-en-burg', lat: 53.076785, lng: 4.905757, name: 'Natuur Waal en Burg', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=fwwiABdfa_A', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-onderwatercam-ecomare', lat: 53.076785, lng: 4.905757, name: 'Onderwatercam Ecomare', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=T0xCKL_IXgk', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-paal-33-kaap-noord', lat: 53.076785, lng: 4.905757, name: 'Paal 33 / Kaap Noord', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=Gq8dWezdEX8', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-paracentrum-texel-tessel-air', lat: 53.076785, lng: 4.905757, name: 'Paracentrum Texel/Tessel Air', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=dqdWrnj_mvI', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-rondkijken-bij-paal-17', lat: 53.076785, lng: 4.905757, name: 'Rondkijken bij Paal 17', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=Hq2Qbcuph4w', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-rondkijken-bij-paal-9', lat: 53.076785, lng: 4.905757, name: 'Rondkijken bij Paal 9', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=YIefLlsHUVQ', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-rondkijken-op-de-golfbaan', lat: 53.076785, lng: 4.905757, name: 'Rondkijken op de golfbaan', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=jKcaVPyz2ac', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-schapenboerderij-texel', lat: 53.041532, lng: 4.795349, name: 'Schapenboerderij Texel', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=0KAaRLr6d2M', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-strand-duinen-bij-de-koog', lat: 53.076785, lng: 4.905757, name: 'Strand/Duinen bij De Koog', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=Di4WiSTX1oY', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-strandpaviljoen-club-17', lat: 53.076785, lng: 4.905757, name: 'Strandpaviljoen Club 17', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=JHSeVkq5ikE', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-strandpaviljoen-paal-17', lat: 53.076785, lng: 4.905757, name: 'Strandpaviljoen Paal 17', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/paal17.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-vanaf-strandhotel-noordzee', lat: 53.076785, lng: 4.905757, name: 'Vanaf Strandhotel Noordzee', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/strandhotel-noordzee.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-veerbootkade', lat: 53.076785, lng: 4.905757, name: 'Veerbootkade', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/veerboot.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-vogel-informatiecentrum', lat: 53.076785, lng: 4.905757, name: 'Vogel informatiecentrum', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=W8EUPeueZjw', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-vuurtoren-restaurant-rj', lat: 53.076785, lng: 4.905757, name: 'Vuurtoren / Restaurant RJ', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/@Texel-Informatie/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-vuurtoren-bij-de-cocksdorp', lat: 53.076785, lng: 4.905757, name: 'Vuurtoren bij De Cocksdorp', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/vuurtoren.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-waddenhaven', lat: 53.044391, lng: 4.858037, name: 'Waddenhaven', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/jachthaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-werkhaven-oudeschild', lat: 53.041357, lng: 4.853246, name: 'Werkhaven Oudeschild', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/werkhaven-oudeschild.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-zeehondenbassin-ecomare', lat: 53.076785, lng: 4.905757, name: 'Zeehondenbassin Ecomare', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/zeehondjes-cam.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-zeehondenbassin-ecomare-2', lat: 53.076785, lng: 4.905757, name: 'Zeehondenbassin Ecomare (2)', city: 'Texel', country: 'Netherlands', external_url: 'https://www.youtube.com/watch?v=YLScvmJDY2o', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-texel-zicht-op-de-koog', lat: 53.076785, lng: 4.905757, name: 'Zicht op De Koog', city: 'Texel', country: 'Netherlands', external_url: 'https://webcams-texel.nl/pages/cameras/de-koog.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-twello-dutchradar-ads-b-and-mlat', lat: 52.238308, lng: 6.100714, name: 'DutchRadar ADS-B and MLAT', city: 'Twello', country: 'Netherlands', external_url: 'https://www.youtube.com/@dutchradar/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-uitgeest-weathercam', lat: 52.530323, lng: 4.709037, name: 'Weathercam', city: 'Uitgeest', country: 'Netherlands', external_url: 'https://www.youtube.com/@weathercamuitgeest/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-urk-webcams-haven', lat: 52.665452, lng: 5.598789, name: 'Webcams Haven', city: 'Urk', country: 'Netherlands', external_url: 'https://www.youtube.com/@alphatech-n5j/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-utrecht-bouw-high-five', lat: 52.090701, lng: 5.121563, name: 'Bouw High Five', city: 'Utrecht', country: 'Netherlands', external_url: 'https://bouw.live/high-five-utrecht/', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-utrecht-bouwcam-beurskwartier', lat: 52.090701, lng: 5.121563, name: 'Bouwcam Beurskwartier', city: 'Utrecht', country: 'Netherlands', external_url: 'https://bouw.live/beurskwartier-utrecht/', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-varik-pleisterplaats-de-bol', lat: 51.823471, lng: 5.367991, name: 'Pleisterplaats De Bol', city: 'Varik', country: 'Netherlands', external_url: 'https://www.youtube.com/@TorenvanVarik/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vianen-ooievaars-stadhuis', lat: 51.988992, lng: 5.093918, name: 'Ooievaars Stadhuis', city: 'Vianen', country: 'Netherlands', external_url: 'https://www.youtube.com/@5heerenlanden/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlaardingen-vanaf-restaurant-t-platje-oost', lat: 51.922786, lng: 4.329563, name: 'Vanaf Restaurant \'t Platje (Oost)', city: 'Vlaardingen', country: 'Netherlands', external_url: 'https://webcam-vlaardingen.nl/pages/cameras/oost.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlaardingen-vanaf-restaurant-t-platje-west', lat: 51.922786, lng: 4.329563, name: 'Vanaf Restaurant \'t Platje (West)', city: 'Vlaardingen', country: 'Netherlands', external_url: 'https://webcam-vlaardingen.nl/pages/cameras/west.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlieland-havenmond', lat: 53.202995, lng: 4.994913, name: 'Havenmond', city: 'Vlieland', country: 'Netherlands', external_url: 'https://webcamvlieland.nl/pages/cameras/havenmond.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlieland-het-posthuys', lat: 53.202995, lng: 4.994913, name: 'Het Posthuys', city: 'Vlieland', country: 'Netherlands', external_url: 'https://webcamvlieland.nl/pages/cameras/posthuys.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlieland-jachthaven-vlieland', lat: 53.296537, lng: 5.090079, name: 'Jachthaven Vlieland', city: 'Vlieland', country: 'Netherlands', external_url: 'https://webcamvlieland.nl/pages/cameras/haven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlieland-vanaf-hotel-zeezicht', lat: 53.202995, lng: 4.994913, name: 'Vanaf Hotel Zeezicht', city: 'Vlieland', country: 'Netherlands', external_url: 'https://www.youtube.com/@ZeezichtVlieland/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlieland-veerkade', lat: 53.202995, lng: 4.994913, name: 'Veerkade', city: 'Vlieland', country: 'Netherlands', external_url: 'https://webcamvlieland.nl/pages/cameras/vvv_vlieland.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-jachthaven-en-het-arsenaal', lat: 51.448093, lng: 3.569799, name: 'Jachthaven en Het Arsenaal', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://webcams-vlissingen.nl/pages/cameras/jachthaven.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-maritiemstream-vlissingen', lat: 51.448093, lng: 3.569799, name: 'MaritiemStream Vlissingen', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://www.youtube.com/@maritiemstream/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-rede-en-ingang-kazematten', lat: 51.448093, lng: 3.569799, name: 'Rede en ingang Kazematten', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://webcams-vlissingen.nl/pages/cameras/rede.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-scheldemonding-vanaf-de-boulevard', lat: 51.448093, lng: 3.569799, name: 'Scheldemonding vanaf de Boulevard', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://webcams-vlissingen.nl/pages/cameras/scheldemonding.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-strand-en-boulevard', lat: 51.448093, lng: 3.569799, name: 'Strand en boulevard', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://webcams-vlissingen.nl/pages/cameras/strand.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-strandpaviljoen-pier-7', lat: 51.448093, lng: 3.569799, name: 'Strandpaviljoen Pier 7', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://www.youtube.com/@Pier7Vlissingen/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-westerschelde-bij-de-oranjemolen', lat: 51.448093, lng: 3.569799, name: 'Westerschelde bij de Oranjemolen', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://www.youtube.com/@johnvlissingenwebcam2437/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlissingen-westerschelde-ferry', lat: 51.444083, lng: 3.596537, name: 'Westerschelde Ferry', city: 'Vlissingen', country: 'Netherlands', external_url: 'https://webcams-vlissingen.nl/pages/cameras/westerschelde-ferry.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vlist-ooievaarsnest-dick-bakker', lat: 51.975027, lng: 4.822489, name: 'Ooievaarsnest (Dick Bakker)', city: 'Vlist', country: 'Netherlands', external_url: 'https://www.youtube.com/@dickbakker1128/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-volendam-de-dijk-van-links-naar-rechts-v-v', lat: 52.496376, lng: 5.068274, name: 'De Dijk van links naar rechts v.v.', city: 'Volendam', country: 'Netherlands', external_url: 'https://www.youtube.com/@DeDijkVolendam/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-vrouwenpolder-strandhotel-duinoord', lat: 51.576602, lng: 3.616578, name: 'Strandhotel Duinoord', city: 'Vrouwenpolder', country: 'Netherlands', external_url: 'https://www.youtube.com/@strandhotelduinoord5815/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-waddinxveen-be-fair-tennis', lat: 52.044331, lng: 4.655853, name: 'Be Fair Tennis', city: 'Waddinxveen', country: 'Netherlands', external_url: 'https://www.youtube.com/@WebCamNL_LIVE1/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-weert-slechtvalken-st-martinuskerk', lat: 51.235583, lng: 5.70508, name: 'Slechtvalken St. Martinuskerk', city: 'Weert', country: 'Netherlands', external_url: 'https://live.netcamviewer.nl/Valkennest-Weert/1052', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-westkapelle-bij-melis-seafood', lat: 51.529331, lng: 3.440786, name: 'Bij Melis Seafood', city: 'Westkapelle', country: 'Netherlands', external_url: 'https://www.youtube.com/@toineschepens9091/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-wijns-dokkumer-ee', lat: 53.294113, lng: 5.878125, name: 'Dokkumer EE', city: 'Wijns', country: 'Netherlands', stream_url: 'https://584b389d712f9.streamlock.net/live/winze.stream/playlist.m3u8', stream_type: 'hls', external_url: 'https://webcam-friesemeren.nl/pages/cameras/wijns-dokkumer-ee.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-woerden-ijsbaan-woerden-live', lat: 52.085926, lng: 4.883294, name: 'IJsbaan Woerden Live', city: 'Woerden', country: 'Netherlands', external_url: 'https://www.youtube.com/@ttswoerden/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-zaandam-nabij-de-wilhelminasluis', lat: 52.442493, lng: 4.829861, name: 'Nabij de Wilhelminasluis', city: 'Zaandam', country: 'Netherlands', external_url: 'https://webcam-zaanzicht.nl/pages/cameras/zaandam.php', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-zandvoort-circuit-zandvoort', lat: 52.389471, lng: 4.542885, name: 'Circuit Zandvoort', city: 'Zandvoort', country: 'Netherlands', external_url: 'https://www.youtube.com/@CircuitZandvoortOfficial/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-zandvoort-ns-station-vast', lat: 52.371984, lng: 4.530221, name: 'NS Station (vast)', city: 'Zandvoort', country: 'Netherlands', external_url: 'https://www.youtube.com/@livefeedzandvoort/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-zandvoort-webcam-de-zeemeermin', lat: 52.371984, lng: 4.530221, name: 'Webcam De Zeemeermin', city: 'Zandvoort', country: 'Netherlands', external_url: 'https://www.youtube.com/@live.webcams.zandvoort/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-zeewolde-vanaf-windturbine-adw-10', lat: 52.345119, lng: 5.458077, name: 'Vanaf windturbine (ADW-10)', city: 'Zeewolde', country: 'Netherlands', external_url: 'https://www.youtube.com/@ADW-10/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-zeewolde-vanaf-windturbine-skipper-93', lat: 52.345119, lng: 5.458077, name: 'Vanaf windturbine (Skipper-93)', city: 'Zeewolde', country: 'Netherlands', external_url: 'https://www.youtube.com/@Skipper-93/live', source: 'Public Webcam' },
  { id: 'pubcam-netherlands-zwolle-nieuwe-veemarkt-bouw', lat: 52.514565, lng: 6.09772, name: 'Nieuwe Veemarkt (Bouw)', city: 'Zwolle', country: 'Netherlands', external_url: 'https://bouw.live/nieuwe-veemarkt-zwolle/', source: 'Public Webcam' },
];

export const EUROPE_PUBLIC_WEBCAMS: CctvCamera[] = [
  // ── Belgium (3) ──
  { id: 'pubcam-belgium-lokeren-webcams-lokeren', lat: 51.148382, lng: 3.944247, name: 'Webcams Lokeren', city: 'Lokeren', country: 'Belgium', external_url: 'https://www.youtube.com/@webcamslokeren8246/live', source: 'Public Webcam' },
  { id: 'pubcam-belgium-stadhuis-sint-niklaas-stadhuis-sint-niklaas', lat: 51.164795, lng: 4.139022, name: 'Stadhuis Sint-Niklaas', city: 'Stadhuis Sint-Niklaas', country: 'Belgium', external_url: 'https://www.youtube.com/@WebcamstadhuisSint-Niklaas/live', source: 'Public Webcam' },
  { id: 'pubcam-belgium-zwin-zwin-natuurpark', lat: 51.358006, lng: 3.345686, name: 'Zwin Natuurpark', city: 'Zwin', country: 'Belgium', external_url: 'https://www.youtube.com/@ZwinNatuurPark/live', source: 'Public Webcam' },
  // ── Croatia (1) ──
  { id: 'pubcam-croatia-hvar-island-of-hvar-live', lat: 43.173941, lng: 16.556516, name: 'Island of Hvar Live', city: 'Hvar', country: 'Croatia', external_url: 'https://www.youtube.com/@HvarLive/live', source: 'Public Webcam' },
  // ── Estonia (1) ──
  { id: 'pubcam-estonia-tallinn-360pano-tallinn', lat: 59.437242, lng: 24.757269, name: '360Pano Tallinn', city: 'Tallinn', country: 'Estonia', external_url: 'https://www.youtube.com/@360panoEu/live', source: 'Public Webcam' },
  // ── Finland (5) ──
  { id: 'pubcam-finland-apukka-apukka-aurora-cam', lat: 66.578928, lng: 26.010825, name: 'Apukka Aurora Cam', city: 'Apukka', country: 'Finland', external_url: 'https://www.youtube.com/@apukkaresortrovaniemi/live', source: 'Public Webcam' },
  { id: 'pubcam-finland-helsinki-port-of-helsinki', lat: 60.16662, lng: 24.943541, name: 'Port of Helsinki', city: 'Helsinki', country: 'Finland', external_url: 'https://www.youtube.com/@PortOfHelsinki/live', source: 'Public Webcam' },
  { id: 'pubcam-finland-kuopio-muikku-live-kuopion-tori', lat: 62.892463, lng: 27.67836, name: 'Muikku LIVE - Kuopion Tori', city: 'Kuopio', country: 'Finland', external_url: 'https://www.youtube.com/@kuopiontori6316/live', source: 'Public Webcam' },
  { id: 'pubcam-finland-levi-levi-ski-resort', lat: 67.784406, lng: 24.855729, name: 'Levi Ski Resort', city: 'Levi', country: 'Finland', external_url: 'https://www.youtube.com/@LeviSkiResort/live', source: 'Public Webcam' },
  { id: 'pubcam-finland-rovaniemi-city-of-rovaniemi', lat: 66.502554, lng: 25.730391, name: 'City of Rovaniemi', city: 'Rovaniemi', country: 'Finland', external_url: 'https://www.youtube.com/@CityofRovaniemi/live', source: 'Public Webcam' },
  // ── Germany (4) ──
  { id: 'pubcam-germany-bremen-visit-bremen', lat: 53.07582, lng: 8.807165, name: 'Visit Bremen', city: 'Bremen', country: 'Germany', external_url: 'https://www.youtube.com/@visitbremen/live', source: 'Public Webcam' },
  { id: 'pubcam-germany-naumburg-saale-stadt-naumburg', lat: 51.152565, lng: 11.809919, name: 'Stadt Naumburg', city: 'Naumburg (Saale)', country: 'Germany', external_url: 'https://www.youtube.com/@stadtnaumburg7037/live', source: 'Public Webcam' },
  { id: 'pubcam-germany-rees-de-rijn-bij-stadt-rees', lat: 51.758124, lng: 6.39566, name: 'De Rijn bij Stadt Rees', city: 'Rees', country: 'Germany', external_url: 'https://www.youtube.com/@stadtrees5435/live', source: 'Public Webcam' },
  { id: 'pubcam-germany-tiergarten-berlin-tiergarten-skyline', lat: 52.509778, lng: 13.35726, name: 'Berlin Tiergarten Skyline', city: 'Tiergarten', country: 'Germany', external_url: 'https://www.youtube.com/@Kohlbecker/live', source: 'Public Webcam' },
  // ── Ireland (2) ──
  { id: 'pubcam-ireland-dublin-port-havenbeelden-dublin', lat: 53.35277, lng: -6.224512, name: 'Havenbeelden Dublin', city: 'Dublin Port', country: 'Ireland', external_url: 'https://www.youtube.com/@dublinportco/live', source: 'Public Webcam' },
  { id: 'pubcam-ireland-temple-bar-temple-bar-dublin', lat: 53.345496, lng: -6.263114, name: 'Temple Bar Dublin', city: 'Temple Bar', country: 'Ireland', external_url: 'https://www.youtube.com/watch?v=u4UZ4UvZXrg', source: 'Public Webcam' },
  // ── Italy (1) ──
  { id: 'pubcam-italy-venezia-i-love-you-venice', lat: 45.437191, lng: 12.33459, name: 'I Love You Venice', city: 'Venezia', country: 'Italy', external_url: 'https://www.youtube.com/@ILoveYouVenice/live', source: 'Public Webcam' },
  // ── Norway (2) ──
  { id: 'pubcam-norway-kirkenes-s-r-varanger-kirkenes', lat: 69.727148, lng: 30.044897, name: 'Sør-Varanger Kirkenes', city: 'Kirkenes', country: 'Norway', external_url: 'https://www.youtube.com/@sr-varangerkommune5151/live', source: 'Public Webcam' },
  { id: 'pubcam-norway-nordkapp-northcape-seafishing', lat: 71.169951, lng: 25.785889, name: 'NorthCape Seafishing', city: 'Nordkapp', country: 'Norway', external_url: 'https://www.youtube.com/@Nordkapp_Havfiske/live', source: 'Public Webcam' },
  // ── Portugal (3) ──
  { id: 'pubcam-portugal-aeroporto-da-madeira-madeira-airport-live', lat: 32.698962, lng: -16.773031, name: 'Madeira Airport Live', city: 'Aeroporto da Madeira', country: 'Portugal', external_url: 'https://www.youtube.com/@madeiraairportlive/live', source: 'Public Webcam' },
  { id: 'pubcam-portugal-aeroporto-humberto-delgado-lisbon-airport-wings', lat: 38.780998, lng: -9.131861, name: 'Lisbon Airport Wings', city: 'Aeroporto Humberto Delgado', country: 'Portugal', external_url: 'https://www.youtube.com/@AirportWingsLisbon/live', source: 'Public Webcam' },
  { id: 'pubcam-portugal-funchal-madeira-web-live', lat: 32.64965, lng: -16.908678, name: 'Madeira Web Live', city: 'Funchal', country: 'Portugal', external_url: 'https://www.youtube.com/@MadeiraWebLive/live', source: 'Public Webcam' },
  // ── Slovenia (1) ──
  { id: 'pubcam-slovenia-kranjska-gora-kransjka-gora', lat: 46.450212, lng: 13.843405, name: 'Kransjka Gora', city: 'Kranjska Gora', country: 'Slovenia', external_url: 'https://www.youtube.com/@KranjskaGoraSi/live', source: 'Public Webcam' },
  // ── Spain (7) ──
  { id: 'pubcam-spain-arrecife-lanzarote-webcam', lat: 28.967112, lng: -13.554615, name: 'Lanzarote webcam', city: 'Arrecife', country: 'Spain', external_url: 'https://www.youtube.com/@LanzaroteWebcam/live', source: 'Public Webcam' },
  { id: 'pubcam-spain-benidorm-benicam-benidorm-webcam', lat: 38.540625, lng: -0.129093, name: 'Benicam Benidorm webcam', city: 'Benidorm', country: 'Spain', external_url: 'https://www.youtube.com/@benicam/live', source: 'Public Webcam' },
  { id: 'pubcam-spain-benidorm-benidorm-live', lat: 38.540625, lng: -0.129093, name: 'Benidorm Live', city: 'Benidorm', country: 'Spain', external_url: 'https://www.youtube.com/@LiveFromSpain/live', source: 'Public Webcam' },
  { id: 'pubcam-spain-cap-blanch-camping-cap-blanch', lat: 38.579101, lng: -0.065326, name: 'Camping Cap-Blanch', city: 'Cap Blanch', country: 'Spain', external_url: 'https://www.youtube.com/@Campingcapblanch25/live', source: 'Public Webcam' },
  { id: 'pubcam-spain-girona-asafegi-girona-centre', lat: 41.979301, lng: 2.819944, name: 'Asafegi Girona Centre', city: 'Girona', country: 'Spain', external_url: 'https://www.youtube.com/@asafecg/live', source: 'Public Webcam' },
  { id: 'pubcam-spain-las-palmas-de-gran-canaria-gran-canaria-live', lat: 28.128869, lng: -15.434902, name: 'Gran Canaria Live', city: 'Las Palmas de Gran Canaria', country: 'Spain', external_url: 'https://www.youtube.com/@grancanarialive/live', source: 'Public Webcam' },
  { id: 'pubcam-spain-san-sebastian-de-la-gomera-wifigomera', lat: 28.091038, lng: -17.111008, name: 'WifiGomera', city: 'San Sebastián de la Gomera', country: 'Spain', external_url: 'https://www.youtube.com/@wifigomera4723/live', source: 'Public Webcam' },
  // ── Switzerland (4) ──
  { id: 'pubcam-switzerland-basel-vanaf-hotel-hecht-basel', lat: 47.558108, lng: 7.587826, name: 'Vanaf Hotel Hecht Basel', city: 'Basel', country: 'Switzerland', external_url: 'https://www.youtube.com/@HotelHecht/live', source: 'Public Webcam' },
  { id: 'pubcam-switzerland-luzern-luzern-live', lat: 47.052144, lng: 8.305812, name: 'Luzern live', city: 'Luzern', country: 'Switzerland', external_url: 'https://www.youtube.com/@Tele1AG/live', source: 'Public Webcam' },
  { id: 'pubcam-switzerland-rheinfall-watervallen-schaffhausen', lat: 47.678362, lng: 8.614871, name: 'Watervallen Schaffhausen', city: 'Rheinfall', country: 'Switzerland', external_url: 'https://www.youtube.com/@schaffhauserland/live', source: 'Public Webcam' },
  { id: 'pubcam-switzerland-zurich-hauptbahnhof-zurich-hauptbahnhof', lat: 47.378101, lng: 8.539364, name: 'Zürich Hauptbahnhof', city: 'Zürich Hauptbahnhof', country: 'Switzerland', external_url: 'https://www.youtube.com/@davidgubler7698/live', source: 'Public Webcam' },
  // ── United Kingdom (9) ──
  { id: 'pubcam-united-kingdom-ammanford-ammanford-wales', lat: 51.795551, lng: -3.996828, name: 'Ammanford (Wales)', city: 'Ammanford', country: 'United Kingdom', external_url: 'https://www.youtube.com/@roger5807/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-broad-haven-pembrokeshire-broad-haven', lat: 51.780369, lng: -5.102378, name: 'Pembrokeshire Broad Haven', city: 'Broad Haven', country: 'United Kingdom', external_url: 'https://www.youtube.com/@havensports1991/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-cowes-solent-ships', lat: 50.763318, lng: -1.298519, name: 'Solent Ships', city: 'Cowes', country: 'United Kingdom', external_url: 'https://www.youtube.com/@SolentShips/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-dorchester-dorset-council', lat: 50.713206, lng: -2.437123, name: 'Dorset Council', city: 'Dorchester', country: 'United Kingdom', external_url: 'https://www.youtube.com/@DorsetCouncilUK/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-isle-of-wight-isle-of-wight', lat: 50.671048, lng: -1.332711, name: 'Isle of Wight', city: 'Isle of Wight', country: 'United Kingdom', external_url: 'https://www.youtube.com/@IsleofWightcom/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-manchester-airport-manchester-airport', lat: 53.350342, lng: -2.280369, name: 'Manchester Airport', city: 'Manchester Airport', country: 'United Kingdom', external_url: 'https://www.youtube.com/@ThinkPlanes/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-oxford-martin-school-oxford-martin-school', lat: 51.75485, lng: -1.254134, name: 'Oxford Martin School', city: 'Oxford Martin School', country: 'United Kingdom', external_url: 'https://www.youtube.com/@OxMartinSchool/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-pickering-north-yorkshire-moors-railway', lat: 54.245659, lng: -0.776563, name: 'North Yorkshire Moors Railway', city: 'Pickering', country: 'United Kingdom', external_url: 'https://www.youtube.com/@NYMR/live', source: 'Public Webcam' },
  { id: 'pubcam-united-kingdom-port-isaac-port-isaac-cornwall', lat: 50.593879, lng: -4.829989, name: 'Port isaac (Cornwall)', city: 'Port Isaac', country: 'United Kingdom', external_url: 'https://www.youtube.com/@OldSchoolPortIsaac/live', source: 'Public Webcam' },
  // ── Vatican City (1) ──
  { id: 'pubcam-vatican-city-piazza-san-pietro-sint-pieterplein', lat: 41.902235, lng: 12.457357, name: 'Sint Pieterplein', city: 'Piazza San Pietro', country: 'Vatican City', external_url: 'https://www.youtube.com/@VaticanNewsEN/live', source: 'Public Webcam' },
];

export const AMERICAS_PUBLIC_WEBCAMS: CctvCamera[] = [
  // ── Belize (1) ──
  { id: 'pubcam-belize-the-belize-zoo-live-stream-zoo', lat: 17.357681, lng: -88.542612, name: 'Live stream Zoo', city: 'The Belize Zoo', country: 'Belize', external_url: 'https://www.youtube.com/@BelizeZoo/live', source: 'Public Webcam' },
  // ── Bonaire (1) ──
  { id: 'pubcam-bonaire-kralendijk-harbour-village-coral-reef', lat: 12.147287, lng: -68.274021, name: 'Harbour Village (Coral Reef)', city: 'Kralendijk', country: 'Bonaire', external_url: 'https://www.youtube.com/@Harbourvillagebonaire/live', source: 'Public Webcam' },
  // ── Canada (4) ──
  { id: 'pubcam-canada-canmore-canmore-alberta', lat: 51.08669, lng: -115.348113, name: 'Canmore (Alberta)', city: 'Canmore', country: 'Canada', external_url: 'https://www.youtube.com/@canmorealbertavideos/live', source: 'Public Webcam' },
  { id: 'pubcam-canada-channel-port-aux-basques-port-au-basques', lat: 47.577663, lng: -59.142419, name: 'Port au Basques', city: 'Channel-Port aux Basques', country: 'Canada', external_url: 'https://www.youtube.com/@customshouse1897/live', source: 'Public Webcam' },
  { id: 'pubcam-canada-collingwood-town-of-collingwood', lat: 44.502723, lng: -80.217238, name: 'Town of Collingwood', city: 'Collingwood', country: 'Canada', external_url: 'https://www.youtube.com/@TownofCollingwood/live', source: 'Public Webcam' },
  { id: 'pubcam-canada-peace-bridge-peace-bridge-authority', lat: 42.907426, lng: -78.909396, name: 'Peace Bridge Authority', city: 'Peace Bridge', country: 'Canada', external_url: 'https://www.youtube.com/@PeaceBridgeAuthority/live', source: 'Public Webcam' },
  // ── Curaçao (1) ──
  { id: 'pubcam-curacao-willemstad-handelskade-en-pontjesbrug', lat: 12.10667, lng: -68.935131, name: 'Handelskade en pontjesbrug', city: 'Willemstad', country: 'Curaçao', external_url: 'https://www.youtube.com/embed/28U-t3fA9ks?autoplay=1&mute=1', source: 'Public Webcam' },
  // ── United States (26) ──
  { id: 'pubcam-united-states-atlantic-city-atlantic-city-boardwalk', lat: 39.364285, lng: -74.422935, name: 'Atlantic City Boardwalk', city: 'Atlantic City', country: 'United States', external_url: 'https://www.youtube.com/@rachelapm/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-breckenridge-breckenridge-mainstreet', lat: 39.482912, lng: -106.046549, name: 'Breckenridge Mainstreet', city: 'Breckenridge', country: 'United States', external_url: 'https://www.youtube.com/@breckenridgeassociatesreal638/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-charlevoix-charlevoix-cams', lat: 45.202075, lng: -84.967639, name: 'Charlevoix Cams', city: 'Charlevoix', country: 'United States', external_url: 'https://www.youtube.com/@CharlevoixCam/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-clearwater-beach-clearwater-jimmy-s-crowsnest', lat: 27.977474, lng: -82.827931, name: 'Clearwater - Jimmy\'s Crowsnest', city: 'Clearwater Beach', country: 'United States', external_url: 'https://www.youtube.com/@jimmyscrowsnest/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-coldwater-city-of-coldwater', lat: 41.941091, lng: -85.003062, name: 'City of Coldwater', city: 'Coldwater', country: 'United States', external_url: 'https://www.youtube.com/@cityofcoldwatermi6619/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-hollywood-city-of-hollywood', lat: 26.011201, lng: -80.14949, name: 'City of Hollywood', city: 'Hollywood', country: 'United States', external_url: 'https://www.youtube.com/@HollywoodFLCH78/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-houston-abc13-houston', lat: 29.758938, lng: -95.367697, name: 'ABC13 Houston', city: 'Houston', country: 'United States', external_url: 'https://www.youtube.com/@ABC13Houston/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-jonesborough-jonesborough-historic-town', lat: 36.294493, lng: -82.473409, name: 'Jonesborough Historic Town', city: 'Jonesborough', country: 'United States', external_url: 'https://www.youtube.com/@Jonesborough/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-leavenworth-leavenworth-washington', lat: 47.596914, lng: -120.661081, name: 'Leavenworth Washington', city: 'Leavenworth', country: 'United States', external_url: 'https://www.youtube.com/@VisitLeavenworthwa/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-los-angeles-international-airport-los-angeles-airportcam', lat: 33.942167, lng: -118.421359, name: 'Los Angeles Airportcam', city: 'Los Angeles International Airport', country: 'United States', external_url: 'https://www.youtube.com/@AIRLINEVIDEOS/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-martha-s-vineyard-go-martha-s-vineyard', lat: 41.392046, lng: -70.620814, name: 'Go Martha\'s Vineyard', city: 'Martha\'s Vineyard', country: 'United States', external_url: 'https://www.youtube.com/@gomv/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-myrtle-beach-myrtle-beach', lat: 33.695646, lng: -78.890041, name: 'Myrtle Beach', city: 'Myrtle Beach', country: 'United States', external_url: 'https://www.youtube.com/@VacationMB/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-newburyport-newburyport-com', lat: 42.811659, lng: -70.871927, name: 'Newburyport.com', city: 'Newburyport', country: 'United States', external_url: 'https://www.youtube.com/@newburyport/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-pacifica-pier-pacifica-pier-and-beach', lat: 37.633378, lng: -122.496171, name: 'Pacifica Pier and Beach', city: 'Pacifica Pier', country: 'United States', external_url: 'https://www.youtube.com/@ChamberlinNature/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-plymouth-three-rivers-parks', lat: 45.006515, lng: -93.46651, name: 'Three Rivers Parks', city: 'Plymouth', country: 'United States', external_url: 'https://www.youtube.com/@ThreeRiversParks/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-port-angeles-port-angeles-fairchild-airport', lat: 48.118146, lng: -123.430741, name: 'Port Angeles/Fairchild Airport', city: 'Port Angeles', country: 'United States', external_url: 'https://www.youtube.com/@portofportangeles6052/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-port-everglades-port-everglades-trafficcams', lat: 26.096852, lng: -80.127261, name: 'Port Everglades trafficcams', city: 'Port Everglades', country: 'United States', external_url: 'https://www.youtube.com/@portevergladestrafficcam8353/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-san-diego-san-diego-webcam-s', lat: 32.71742, lng: -117.162772, name: 'San Diego Webcam(s)', city: 'San Diego', country: 'United States', external_url: 'https://www.youtube.com/@SanDiegoWebCam/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-san-diego-zoo-san-diego-zoo', lat: 32.735987, lng: -117.150654, name: 'San Diego Zoo', city: 'San Diego Zoo', country: 'United States', external_url: 'https://www.youtube.com/@SanDiegoZoo/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-seattle-tacoma-international-airport-seatac-airport-mount-rainier', lat: 47.447567, lng: -122.308016, name: 'SeaTac Airport (Mount Rainier)', city: 'Seattle-Tacoma International Airport', country: 'United States', external_url: 'https://www.youtube.com/@RainierAviation/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-southampton-hamptons-cams', lat: 40.884248, lng: -72.389713, name: 'Hamptons Cams', city: 'Southampton', country: 'United States', external_url: 'https://www.youtube.com/@Hamptons/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-st-augustine-st-augustine-live', lat: 29.894695, lng: -81.314539, name: 'St. Augustine Live', city: 'St. Augustine', country: 'United States', external_url: 'https://www.youtube.com/@staugustinelive/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-sugarloaf-mountain-sugarloaf-mountain', lat: 45.031811, lng: -70.313101, name: 'Sugarloaf Mountain', city: 'Sugarloaf Mountain', country: 'United States', external_url: 'https://www.youtube.com/@Sugarloafers/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-tehachapi-tehachapi-live-trains', lat: 35.132188, lng: -118.448974, name: 'Tehachapi Live Trains', city: 'Tehachapi', country: 'United States', external_url: 'https://www.youtube.com/@TehachapiLiveTrainCam/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-university-of-north-dakota-und-dept-of-atmospheric-sciences', lat: 47.926541, lng: -97.072121, name: 'UND Dept. of Atmospheric Sciences', city: 'University of North Dakota', country: 'United States', external_url: 'https://www.youtube.com/@UNDAtmosphericSciences/live', source: 'Public Webcam' },
  { id: 'pubcam-united-states-winter-garden-winter-garden', lat: 28.565665, lng: -81.585674, name: 'Winter Garden', city: 'Winter Garden', country: 'United States', external_url: 'https://www.youtube.com/@wintergardenheritagefoundation/live', source: 'Public Webcam' },
  // ── US Virgin Islands (1) ──
  { id: 'pubcam-us-virgin-islands-cruz-bay-saint-john', lat: 18.330821, lng: -64.794481, name: 'Saint John', city: 'Cruz Bay', country: 'US Virgin Islands', external_url: 'https://www.youtube.com/@GR8XVilla/live', source: 'Public Webcam' },
];

export const REST_PUBLIC_WEBCAMS: CctvCamera[] = [
  // ── Australia (1) ──
  { id: 'pubcam-australia-sydney-sydney-live-camera', lat: -33.869844, lng: 151.208285, name: 'Sydney Live Camera', city: 'Sydney', country: 'Australia', external_url: 'https://www.youtube.com/@sydneylivecamera/live', source: 'Public Webcam' },
  // ── Japan (1) ──
  { id: 'pubcam-japan-shinjuku-tokyo-shinjuku-live', lat: 35.693763, lng: 139.703632, name: 'Tokyo Shinjuku Live', city: 'Shinjuku', country: 'Japan', external_url: 'https://www.youtube.com/@livetokyoshinjukulivech5482/live', source: 'Public Webcam' },
  // ── Philippines (1) ──
  { id: 'pubcam-philippines-davao-city-agdao-davao-city', lat: 7.064831, lng: 125.608062, name: 'Agdao, Davao City', city: 'Davao City', country: 'Philippines', external_url: 'https://www.youtube.com/@JazBazPhilippines/live', source: 'Public Webcam' },
  // ── Russia (2) ──
  { id: 'pubcam-russia-lensk-lensk-lr', lat: 60.714549, lng: 114.917212, name: 'Lensk LR', city: 'Lensk', country: 'Russia', external_url: 'https://www.youtube.com/@LenskLR/live', source: 'Public Webcam' },
  { id: 'pubcam-russia-sankt-peterburg-mobotix-st-petersburg', lat: 59.960674, lng: 30.158655, name: 'Mobotix St. Petersburg', city: 'Sankt-Peterburg', country: 'Russia', external_url: 'https://www.youtube.com/@msbud2/live', source: 'Public Webcam' },
  // ── South Korea (1) ──
  { id: 'pubcam-south-korea-nowon-gu-healing-nowon-live', lat: 37.654, lng: 127.0567, name: 'Healing Nowon Live', city: 'Nowon-gu', country: 'South Korea', external_url: 'https://www.youtube.com/@healinglivenowon7260/live', source: 'Public Webcam' },
  // ── Taiwan (1) ──
  { id: 'pubcam-taiwan-taoyuan-taoyuan-travel', lat: 24.992999, lng: 121.301, name: 'Taoyuan Travel', city: 'Taoyuan', country: 'Taiwan', external_url: 'https://www.youtube.com/@TaoyuanTravel/live', source: 'Public Webcam' },
  // ── Thailand (2) ──
  { id: 'pubcam-thailand-ko-samui-the-real-samui-webcams', lat: 9.507155, lng: 99.995756, name: 'The Real Samui Webcams', city: 'Ko Samui', country: 'Thailand', external_url: 'https://www.youtube.com/@TheRealSamuiWebcam/live', source: 'Public Webcam' },
  { id: 'pubcam-thailand-pattaya-soi-buakhao-pattaya-live', lat: 12.936692, lng: 100.8865, name: 'Soi Buakhao, Pattaya Live', city: 'Pattaya', country: 'Thailand', external_url: 'https://www.youtube.com/@ismannen/live', source: 'Public Webcam' },
];
