import type { CctvCamera } from './types';

/**
 * OSIRIS — SkylineWebcams public live cameras in the United States (GENERATED).
 *
 * The US was the one gap in Skyline's coverage here: Latin America, the
 * Caribbean, Africa, Asia and much of Europe already had lists, and the States
 * had nothing but traffic-authority feeds. This adds the beaches, piers,
 * boardwalks and downtowns those feeds never point at.
 *
 * **Every camera in this file is live video, not a snapshot.** Each Skyline
 * page carries a YouTube broadcast id in its structured data, which is what
 * these embed. That is a deliberate departure from the other Skyline lists,
 * which serve poster frames through /api/cctv/proxy, and it is not a stylistic
 * one: of the 90 US cameras that had a poster frame but no broadcast id, the
 * CDN image was refetched 30 seconds apart and **not one of the 90 had
 * changed**. Every one of those frames is frozen. Shipping them as `feed_url`
 * would have put ninety pins on the map showing a still picture of some
 * indeterminate past, which is the thing a live camera layer must not do, so
 * they are excluded entirely rather than shown.
 *
 * 120 of 302 enumerated US cameras are here. The rest are dropped for one
 * of two honest reasons: no broadcast id (the frozen-poster case above), or no
 * coordinates - Nominatim could not place the camera's own name or its city, and
 * a camera that cannot be placed cannot go on a map.
 *
 * The `city` is the town in the camera's own Skyline path, which is accurate
 * everywhere except New York: Skyline files the whole state under one
 * /new-york/new-york/ bucket, so those seven caption as "New York" the state.
 * That is true of all of them - Sag Harbor and East Hampton included - and
 * their names already say which town they are in. Inferring a town from the
 * geocoder was the alternative and it is worse: it puts the Brooklyn Bridge
 * camera at a college in Dumbo and the Manhattan one at Columbia in Harlem.
 *
 * Coordinates are from OpenStreetMap Nominatim, each checked against a bounding
 * box for the state it claims to be in, so a geocode that wandered into another
 * state was thrown away rather than plotted.
 */

export const US_SKYLINE_CAMERAS: CctvCamera[] = [
  // ── California (10) ──
  { id: 'sky-us-hummingbird-nest-california-2825', lat: 34.2870558, lng: -118.6562532, name: 'Hummingbird Nest - California', city: 'Rowland Heights', country: 'US', stream_url: 'https://www.youtube.com/embed/pXe8MpU7uzk?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/rowland-heights/hummingbird-nest.html', source: 'SkylineWebcams' },
  { id: 'sky-us-mammoth-mountain-ski-area-california-3596', lat: 37.6501547, lng: -119.037553, name: 'Mammoth Mountain Ski Area - California', city: 'Mammoth Lakes', country: 'US', stream_url: 'https://www.youtube.com/embed/MwHWDokyUhw?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/mammoth-lakes/mammoth-mountain.html', source: 'SkylineWebcams' },
  { id: 'sky-us-orange-california-4410', lat: 33.750631, lng: -117.8722311, name: 'Orange - California', city: 'Orange', country: 'US', stream_url: 'https://www.youtube.com/embed/AShvF9ILGkc?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/orange/plaza.html', source: 'SkylineWebcams' },
  { id: 'sky-us-pacifica-pier-california-5137', lat: 37.6333784, lng: -122.496171, name: 'Pacifica Pier - California', city: 'Pacifica', country: 'US', stream_url: 'https://www.youtube.com/embed/bJ3iYpvbC5Y?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/pacifica/pier.html', source: 'SkylineWebcams' },
  { id: 'sky-us-pine-cove-idyllwild-california-3572', lat: 33.7435635, lng: -116.7237619, name: 'Pine Cove-Idyllwild - California', city: 'Idyllwild Pine Cove', country: 'US', stream_url: 'https://www.youtube.com/embed/Lzv9U8cFAa0?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/idyllwild-pine-cove/idyllwild-pine-cove.html', source: 'SkylineWebcams' },
  { id: 'sky-us-san-francisco-1833', lat: 37.7879363, lng: -122.4075201, name: 'San Francisco', city: 'San Francisco', country: 'US', stream_url: 'https://www.youtube.com/embed/G8RIAgPxaMc?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/san-francisco/san-francisco.html', source: 'SkylineWebcams' },
  { id: 'sky-us-san-francisco-castro-street-1832', lat: 37.7688708, lng: -122.4268065, name: 'San Francisco - Castro Street', city: 'San Francisco', country: 'US', stream_url: 'https://www.youtube.com/embed/cHSllC2fJ4Q?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/san-francisco/san-francisco-castro-street.html', source: 'SkylineWebcams' },
  { id: 'sky-us-san-juan-capistrano-california-2457', lat: 33.5016932, lng: -117.6625509, name: 'San Juan Capistrano - California', city: 'San Juan Capistrano', country: 'US', stream_url: 'https://www.youtube.com/embed/-g1qAvXyIyQ?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/san-juan-capistrano/railfan.html', source: 'SkylineWebcams' },
  { id: 'sky-us-south-lake-tahoe-airport-4411', lat: 38.892547, lng: -119.998651, name: 'South Lake Tahoe - Airport', city: 'South Lake Tahoe', country: 'US', stream_url: 'https://www.youtube.com/embed/Gq1kM9PqNg4?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/south-lake-tahoe/airport.html', source: 'SkylineWebcams' },
  { id: 'sky-us-venice-beach-los-angeles-2806', lat: 33.9799601, lng: -118.468771, name: 'Venice Beach - Los Angeles', city: 'Los Angeles', country: 'US', stream_url: 'https://www.youtube.com/embed/98jOtUeM3m8?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/california/los-angeles/venice-beach.html', source: 'SkylineWebcams' },
  // ── Florida (35) ──
  { id: 'sky-us-anna-maria-island-florida-3463', lat: 27.529362, lng: -82.7324345, name: 'Anna Maria Island - Florida', city: 'Anna Maria Island', country: 'US', stream_url: 'https://www.youtube.com/embed/EmHLP80PMU0?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/anna-maria-island/white-sands-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-bald-eagle-2685', lat: 30.4027725, lng: -81.6444535, name: 'Bald Eagle', city: 'Jacksonville', country: 'US', stream_url: 'https://www.youtube.com/embed/JfI_WNnE8fo?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/jacksonville/bald-eagle.html', source: 'SkylineWebcams' },
  { id: 'sky-us-beach-of-clearwater-florida-4581', lat: 27.987788, lng: -82.8268077, name: 'Beach of Clearwater - Florida', city: 'Clearwater', country: 'US', stream_url: 'https://www.youtube.com/embed/OpuCITeGEus?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/clearwater/beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-bokeelia-florida-5208', lat: 26.700581, lng: -82.172197, name: 'Bokeelia - Florida', city: 'Pine Island', country: 'US', stream_url: 'https://www.youtube.com/embed/1yGtTaJ33jY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/pine-island/bookelia.html', source: 'SkylineWebcams' },
  { id: 'sky-us-clearwater-beach-florida-867', lat: 27.9774736, lng: -82.8279313, name: 'Clearwater Beach - Florida', city: 'Clearwater', country: 'US', stream_url: 'https://www.youtube.com/embed/2jgXAQTOAlw?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/clearwater/clearwater-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-dania-beach-florida-1928', lat: 26.0524224, lng: -80.143929, name: 'Dania Beach - Florida', city: 'Dania Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/o1eTLR7Degs?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/dania-beach/dania-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-deerfield-beach-3180', lat: 26.318342, lng: -80.0996306, name: 'Deerfield Beach', city: 'Deerfield Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/1PLqzPwXP0c?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/deerfield-beach/deerfield-beach-sport.html', source: 'SkylineWebcams' },
  { id: 'sky-us-deerfield-beach-florida-1930', lat: 26.318342, lng: -80.0996306, name: 'Deerfield Beach - Florida', city: 'Deerfield Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/hIeFPNHfuoY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/deerfield-beach/deerfield-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-downtown-stuart-florida-2694', lat: 27.1892076, lng: -80.2512539, name: 'Downtown Stuart - Florida', city: 'Stuart', country: 'US', stream_url: 'https://www.youtube.com/embed/r-Mqjc7I5JA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/stuart/downtown.html', source: 'SkylineWebcams' },
  { id: 'sky-us-dune-allen-beach-florida-4875', lat: 30.3506795, lng: -86.2423271, name: 'Dune Allen Beach - Florida', city: 'Santa Rosa', country: 'US', stream_url: 'https://www.youtube.com/embed/xNZBPxx8ykg?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/santa-rosa/dune-allen-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-eagle-nest-2897', lat: 26.7822903, lng: -82.1914817, name: 'Eagle Nest', city: 'Miami', country: 'US', stream_url: 'https://www.youtube.com/embed/P5ZlAfoO_7o?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/miami/dade-county-eagle-nest.html', source: 'SkylineWebcams' },
  { id: 'sky-us-elbo-room-bar-4283', lat: 26.1194612, lng: -80.1047091, name: 'Elbo Room Bar', city: 'Fort Lauderdale', country: 'US', stream_url: 'https://www.youtube.com/embed/YWs0HMRVCBY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/fort-lauderdale/elbo-room-band.html', source: 'SkylineWebcams' },
  { id: 'sky-us-fort-lauderdale-3366', lat: 26.1223084, lng: -80.1433786, name: 'Fort Lauderdale', city: 'Fort Lauderdale', country: 'US', stream_url: 'https://www.youtube.com/embed/Lpm-C_Gz6yM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/fort-lauderdale/port-everglades-3.html', source: 'SkylineWebcams' },
  { id: 'sky-us-fort-lauderdale-port-everglades-3059', lat: 26.0984266, lng: -80.1230716, name: 'Fort Lauderdale - Port Everglades', city: 'Fort Lauderdale', country: 'US', stream_url: 'https://www.youtube.com/embed/67-73mgWDf0?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/fort-lauderdale/port-everglades.html', source: 'SkylineWebcams' },
  { id: 'sky-us-frenchy-s-clearwater-beach-florida-1926', lat: 27.9834707, lng: -82.8278375, name: 'Frenchy\'s Clearwater Beach - Florida', city: 'Clearwater', country: 'US', stream_url: 'https://www.youtube.com/embed/rxBBRLWF0mM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/clearwater/frenchys-clearwater-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-hollywood-beach-florida-1896', lat: 30.2540906, lng: -85.9568811, name: 'Hollywood Beach - Florida', city: 'Hollywood', country: 'US', stream_url: 'https://www.youtube.com/embed/pcPwY5Qg594?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/hollywood/hollywood-beach-theatre.html', source: 'SkylineWebcams' },
  { id: 'sky-us-hollywood-beach-broadwalk-florida-1892', lat: 26.0195204, lng: -80.1151353, name: 'Hollywood Beach Broadwalk - Florida', city: 'Hollywood', country: 'US', stream_url: 'https://www.youtube.com/embed/cmkAbDUEoyA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/hollywood/hollywood-beach-broadwalk.html', source: 'SkylineWebcams' },
  { id: 'sky-us-key-west-duval-street-4228', lat: 24.5475572, lng: -81.796909, name: 'Key West - Duval Street', city: 'Key West', country: 'US', stream_url: 'https://www.youtube.com/embed/3bXyYuk-XK0?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/key-west/duval-street.html', source: 'SkylineWebcams' },
  { id: 'sky-us-laguna-beach-panama-city-beach-4360', lat: 30.2472953, lng: -85.9438158, name: 'Laguna Beach - Panama City Beach', city: 'Panama City Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/nT8aBQx8OS4?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/panama-city-beach/laguna-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-marathon-florida-1929', lat: 24.7137524, lng: -81.0903512, name: 'Marathon - Florida', city: 'Marathon', country: 'US', stream_url: 'https://www.youtube.com/embed/jE4og3o_SXs?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/marathon/marathon.html', source: 'SkylineWebcams' },
  { id: 'sky-us-miramar-beach-florida-1869', lat: 30.377985, lng: -86.3616979, name: 'Miramar Beach - Florida', city: 'Miramar Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/CVgBM39TOh8?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/miramar-beach/miramar-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-new-smyrna-florida-3908', lat: 29.0502512, lng: -80.9331273, name: 'New Smyrna - Florida', city: 'New Smyrna', country: 'US', stream_url: 'https://www.youtube.com/embed/550p9smwjPM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/new-smyrna/new-smyrna.html', source: 'SkylineWebcams' },
  { id: 'sky-us-ormond-by-the-sea-5110', lat: 29.3451855, lng: -81.0683775, name: 'Ormond by the Sea', city: 'Ormond Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/p1s7EdZgGvU?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/ormond-beach/ormond-by-the-sea.html', source: 'SkylineWebcams' },
  { id: 'sky-us-panama-city-beach-florida-4316', lat: 30.1765914, lng: -85.805386, name: 'Panama City Beach - Florida', city: 'Panama City Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/XSl1FZzhiQI?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/panama-city-beach/beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-perdido-key-3295', lat: 30.2995133, lng: -87.4292511, name: 'Perdido Key', city: 'Perdido Key', country: 'US', stream_url: 'https://www.youtube.com/embed/Qoouv_9QG5Q?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/perdido-key/mirabella-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-port-of-miami-florida-4679', lat: 25.7735142, lng: -80.1691962, name: 'Port of Miami - Florida', city: 'Miami', country: 'US', stream_url: 'https://www.youtube.com/embed/m1R-LmvVt30?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/miami/port.html', source: 'SkylineWebcams' },
  { id: 'sky-us-satellite-beach-florida-3106', lat: 28.1760051, lng: -80.5904623, name: 'Satellite Beach - Florida', city: 'Satellite Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/6B3Dpn1TuNQ?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/satellite-beach/grand-canal.html', source: 'SkylineWebcams' },
  { id: 'sky-us-siesta-key-beach-florida-4491', lat: 27.2463813, lng: -82.5357214, name: 'Siesta Key Beach - Florida', city: 'Sarasota', country: 'US', stream_url: 'https://www.youtube.com/embed/tHChKBUnXhY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/sarasota/siesta-key-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-st-augustine-3836', lat: 29.8946952, lng: -81.3145395, name: 'St. Augustine', city: 'St Augustine', country: 'US', stream_url: 'https://www.youtube.com/embed/mYbn_umeenk?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/st-augustine/st-augustine.html', source: 'SkylineWebcams' },
  { id: 'sky-us-st-augustine-bridge-of-lions-3161', lat: 29.8917258, lng: -81.309165, name: 'St. Augustine - Bridge of Lions', city: 'St Augustine', country: 'US', stream_url: 'https://www.youtube.com/embed/0lox0s8zNcU?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/st-augustine/bridge-of-lions.html', source: 'SkylineWebcams' },
  { id: 'sky-us-st-george-island-florida-5056', lat: 29.6926135, lng: -84.7805281, name: 'St. George Island - Florida', city: 'St George Island', country: 'US', stream_url: 'https://www.youtube.com/embed/99rql3wym9I?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/st-george-island/st-george-island.html', source: 'SkylineWebcams' },
  { id: 'sky-us-sterling-reef-panama-city-beach-4097', lat: 30.1886376, lng: -85.8280014, name: 'Sterling Reef - Panama City Beach', city: 'Panama City Beach', country: 'US', stream_url: 'https://www.youtube.com/embed/Y82E6_IVEdY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/panama-city-beach/sterling-reef.html', source: 'SkylineWebcams' },
  { id: 'sky-us-tampa-florida-3368', lat: 27.9449854, lng: -82.4583107, name: 'Tampa - Florida', city: 'Tampa', country: 'US', stream_url: 'https://www.youtube.com/embed/QvNWCIOaB4Y?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/tampa/tampa.html', source: 'SkylineWebcams' },
  { id: 'sky-us-watersound-florida-4623', lat: 30.28815, lng: -86.0452972, name: 'Watersound - Florida', city: 'Watersound', country: 'US', stream_url: 'https://www.youtube.com/embed/uNuMsdostN8?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/watersound/watersound.html', source: 'SkylineWebcams' },
  { id: 'sky-us-winter-garden-florida-1885', lat: 28.5656649, lng: -81.5856742, name: 'Winter Garden - Florida', city: 'Winter Garden', country: 'US', stream_url: 'https://www.youtube.com/embed/sKcmQQqzQcM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/florida/winter-garden/winter-garden.html', source: 'SkylineWebcams' },
  // ── Hawaii (5) ──
  { id: 'sky-us-honolulu-ala-moana-4299', lat: 21.2916084, lng: -157.8452975, name: 'Honolulu - Ala Moana', city: 'Honolulu', country: 'US', stream_url: 'https://www.youtube.com/embed/y5XS3fMISRk?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/hawaii/honolulu/ala-moana.html', source: 'SkylineWebcams' },
  { id: 'sky-us-honolulu-hawaii-3545', lat: 21.2982795, lng: -157.8186932, name: 'Honolulu - Hawaii', city: 'Honolulu', country: 'US', stream_url: 'https://www.youtube.com/embed/WIUg8wzhq1g?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/hawaii/honolulu/honolulu.html', source: 'SkylineWebcams' },
  { id: 'sky-us-kihei-hawaii-4178', lat: 20.7476261, lng: -156.4549898, name: 'Kihei - Hawaii', city: 'Maui', country: 'US', stream_url: 'https://www.youtube.com/embed/hPvl6IACa2k?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/hawaii/maui/kihei.html', source: 'SkylineWebcams' },
  { id: 'sky-us-kilauea-volcano-hawaii-3842', lat: 19.4138647, lng: -155.275811, name: 'Kilauea Volcano - Hawaii', city: 'Pahoa', country: 'US', stream_url: 'https://www.youtube.com/embed/gXKuUyKt8mc?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/hawaii/pahoa/kilauea-volcano.html', source: 'SkylineWebcams' },
  { id: 'sky-us-lawai-beach-2761', lat: 21.8816129, lng: -159.4760203, name: 'Lawai Beach', city: 'Lawaii', country: 'US', stream_url: 'https://www.youtube.com/embed/3ATYHKN2hIg?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/hawaii/lawaii/beach.html', source: 'SkylineWebcams' },
  // ── Maryland (2) ──
  { id: 'sky-us-baltimora-maryland-4777', lat: 39.3483538, lng: -76.6159318, name: 'Baltimora - Maryland', city: 'Baltimora', country: 'US', stream_url: 'https://www.youtube.com/embed/fE02qa-Phs0?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/maryland/baltimora/port.html', source: 'SkylineWebcams' },
  { id: 'sky-us-havre-de-grace-maryland-2039', lat: 39.5429948, lng: -76.090135, name: 'Havre de Grace - Maryland', city: 'Havre De Grace', country: 'US', stream_url: 'https://www.youtube.com/embed/uOC4CPHiOFM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/maryland/havre-de-grace/havre-de-grace.html', source: 'SkylineWebcams' },
  // ── Massachusetts (11) ──
  { id: 'sky-us-boston-charles-river-2050', lat: 42.3706247, lng: -71.0605267, name: 'Boston - Charles River', city: 'Boston', country: 'US', stream_url: 'https://www.youtube.com/embed/UZ20XjGsCCs?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/boston/boston-charles-river.html', source: 'SkylineWebcams' },
  { id: 'sky-us-boston-harbor-2042', lat: 42.3417649, lng: -70.9661596, name: 'Boston Harbor', city: 'Boston', country: 'US', stream_url: 'https://www.youtube.com/embed/3I_cIS24AfY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/boston/boston-harbor.html', source: 'SkylineWebcams' },
  { id: 'sky-us-cahoon-hollow-massachusetts-3907', lat: 41.9445495, lng: -69.9855768, name: 'Cahoon Hollow - Massachusetts', city: 'Cahoon Hollow', country: 'US', stream_url: 'https://www.youtube.com/embed/_3LjfzI7EIM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/cahoon-hollow/cahoon-hollow.html', source: 'SkylineWebcams' },
  { id: 'sky-us-fitchburg-massachusetts-2871', lat: 42.5533346, lng: -71.8457679, name: 'Fitchburg - Massachusetts', city: 'Fitchburg', country: 'US', stream_url: 'https://www.youtube.com/embed/liNviF0C_Bc?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/fitchburg/downtown.html', source: 'SkylineWebcams' },
  { id: 'sky-us-gloucester-massachusetts-4074', lat: 42.6546891, lng: -70.7053475, name: 'Gloucester - Massachusetts', city: 'Gloucester', country: 'US', stream_url: 'https://www.youtube.com/embed/_j1qgdMnifk?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/gloucester/gloucester.html', source: 'SkylineWebcams' },
  { id: 'sky-us-harwich-port-2048', lat: 41.6679786, lng: -70.0740434, name: 'Harwich Port', city: 'Harwich Port', country: 'US', stream_url: 'https://www.youtube.com/embed/REpNAzupM9Y?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/harwich-port/harwich-port.html', source: 'SkylineWebcams' },
  { id: 'sky-us-nantucket-massachusetts-3614', lat: 41.2936311, lng: -70.040985, name: 'Nantucket - Massachusetts', city: 'Nantucket', country: 'US', stream_url: 'https://www.youtube.com/embed/sp-FHZY95QM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/nantucket/nantucket.html', source: 'SkylineWebcams' },
  { id: 'sky-us-newburyport-market-square-4375', lat: 42.8111569, lng: -70.8700614, name: 'Newburyport - Market Square', city: 'Newburyport', country: 'US', stream_url: 'https://www.youtube.com/embed/VsuSbXPN93o?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/newburyport/market-square.html', source: 'SkylineWebcams' },
  { id: 'sky-us-newburyport-massachusetts-4237', lat: 42.8122389, lng: -70.8698845, name: 'Newburyport - Massachusetts', city: 'Newburyport', country: 'US', stream_url: 'https://www.youtube.com/embed/hYnWDuvXXvc?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/newburyport/newburyport.html', source: 'SkylineWebcams' },
  { id: 'sky-us-newburyport-state-street-4388', lat: 42.8089476, lng: -70.8712131, name: 'Newburyport - State Street', city: 'Newburyport', country: 'US', stream_url: 'https://www.youtube.com/embed/CGrmP5woZz8?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/newburyport/state-street.html', source: 'SkylineWebcams' },
  { id: 'sky-us-westfield-park-square-2520', lat: 42.1289373, lng: -72.7474638, name: 'Westfield - Park Square', city: 'Westfield', country: 'US', stream_url: 'https://www.youtube.com/embed/JHEmvHrNfJg?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/massachusetts/westfield/park-square.html', source: 'SkylineWebcams' },
  // ── Michigan (12) ──
  { id: 'sky-us-algonac-michigan-2496', lat: 42.6260905, lng: -82.5262447, name: 'Algonac - Michigan', city: 'Algonac', country: 'US', stream_url: 'https://www.youtube.com/embed/g4mpc2I5lhc?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/algonac/algonac.html', source: 'SkylineWebcams' },
  { id: 'sky-us-charlevoix-michigan-2108', lat: 45.0454534, lng: -83.2235145, name: 'Charlevoix - Michigan', city: 'Charlevoix', country: 'US', stream_url: 'https://www.youtube.com/embed/yWIHgMW2yVQ?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/charlevoix/charlevoix.html', source: 'SkylineWebcams' },
  { id: 'sky-us-coldwater-michigan-2104', lat: 41.9614805, lng: -84.980973, name: 'Coldwater - Michigan', city: 'Coldwater', country: 'US', stream_url: 'https://www.youtube.com/embed/1H0iTzv2jiQ?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/coldwater/coldwater.html', source: 'SkylineWebcams' },
  { id: 'sky-us-coldwater-monroe-street-2103', lat: 41.9418472, lng: -85.0023879, name: 'Coldwater - Monroe Street', city: 'Coldwater', country: 'US', stream_url: 'https://www.youtube.com/embed/5E84M6cSJME?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/coldwater/coldwater-monroe-street.html', source: 'SkylineWebcams' },
  { id: 'sky-us-leland-michigan-2106', lat: 45.0228754, lng: -85.7601164, name: 'Leland - Michigan', city: 'Leland', country: 'US', stream_url: 'https://www.youtube.com/embed/s7sY1waeOf4?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/leland/leland-michigan.html', source: 'SkylineWebcams' },
  { id: 'sky-us-marine-city-michigan-2847', lat: 42.7185017, lng: -82.5081709, name: 'Marine City - Michigan', city: 'Marine City', country: 'US', stream_url: 'https://www.youtube.com/embed/NqvRpsavyWg?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/marine-city/st-clair-river.html', source: 'SkylineWebcams' },
  { id: 'sky-us-marshall-michigan-4062', lat: 42.2699155, lng: -84.9908465, name: 'Marshall - Michigan', city: 'Marshall', country: 'US', stream_url: 'https://www.youtube.com/embed/ccN7Cgs4XfI?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/marshall/marshall.html', source: 'SkylineWebcams' },
  { id: 'sky-us-port-huron-michigan-2483', lat: 42.9883221, lng: -82.4264974, name: 'Port Huron - Michigan', city: 'Port Huron', country: 'US', stream_url: 'https://www.youtube.com/embed/AwP_Q6IGwFs?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/port-huron/port-huron.html', source: 'SkylineWebcams' },
  { id: 'sky-us-sanford-michigan-3378', lat: 43.6700864, lng: -84.3692344, name: 'Sanford - Michigan', city: 'Sanford', country: 'US', stream_url: 'https://www.youtube.com/embed/GsVSmSZ1PzE?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/sanford/dam.html', source: 'SkylineWebcams' },
  { id: 'sky-us-south-haven-michigan-2111', lat: 42.4065234, lng: -86.274344, name: 'South Haven - Michigan', city: 'South Haven', country: 'US', stream_url: 'https://www.youtube.com/embed/G-tlKF32_p4?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/south-haven/south-haven.html', source: 'SkylineWebcams' },
  { id: 'sky-us-st-clair-michigan-2846', lat: 42.9620219, lng: -82.4785522, name: 'St. Clair - Michigan', city: 'St Clair', country: 'US', stream_url: 'https://www.youtube.com/embed/yu0pKQSvYX8?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/st-clair/river.html', source: 'SkylineWebcams' },
  { id: 'sky-us-vicksburg-michigan-3431', lat: 42.1142953, lng: -85.5338549, name: 'Vicksburg - Michigan', city: 'Vicksburg', country: 'US', stream_url: 'https://www.youtube.com/embed/_TMwp4Yt1nc?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/michigan/vicksburg/prairie-street.html', source: 'SkylineWebcams' },
  // ── Minnesota (7) ──
  { id: 'sky-us-bemidji-minnesota-2150', lat: 47.5031897, lng: -94.8828227, name: 'Bemidji - Minnesota', city: 'Bemidji', country: 'US', stream_url: 'https://www.youtube.com/embed/1keU6WOoDbw?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/minnesota/bemidji/bemidji.html', source: 'SkylineWebcams' },
  { id: 'sky-us-duluth-bay-minnesota-2117', lat: 46.7646622, lng: -92.0946344, name: 'Duluth Bay - Minnesota', city: 'Duluth', country: 'US', stream_url: 'https://www.youtube.com/embed/EbVlhVeD3jA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/minnesota/duluth/duluth-bay.html', source: 'SkylineWebcams' },
  { id: 'sky-us-duluth-canal-minnesota-3574', lat: 46.7795817, lng: -92.0909084, name: 'Duluth Canal - Minnesota', city: 'Duluth', country: 'US', stream_url: 'https://www.youtube.com/embed/HPS48TMmNag?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/minnesota/duluth/canal.html', source: 'SkylineWebcams' },
  { id: 'sky-us-duluth-harbor-minnesota-3625', lat: 46.7824037, lng: -92.0968143, name: 'Duluth Harbor - Minnesota', city: 'Duluth', country: 'US', stream_url: 'https://www.youtube.com/embed/lXxV3gkhaBA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/minnesota/duluth/harbor.html', source: 'SkylineWebcams' },
  { id: 'sky-us-duluth-harbor-basin-minnesota-2116', lat: 46.7646622, lng: -92.0946344, name: 'Duluth Harbor Basin - Minnesota', city: 'Duluth', country: 'US', stream_url: 'https://www.youtube.com/embed/c1kfkIoF0k0?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/minnesota/duluth/duluth-harbor-basin.html', source: 'SkylineWebcams' },
  { id: 'sky-us-duluth-lighthouse-minnesota-3219', lat: 46.7800671, lng: -92.0877042, name: 'Duluth Lighthouse - Minnesota', city: 'Duluth', country: 'US', stream_url: 'https://www.youtube.com/embed/nCf7X2cPDAY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/minnesota/duluth/lighthouse.html', source: 'SkylineWebcams' },
  { id: 'sky-us-grand-rapids-minnesota-2118', lat: 47.2425412, lng: -93.494691, name: 'Grand Rapids - Minnesota', city: 'Grand Rapids', country: 'US', stream_url: 'https://www.youtube.com/embed/b7lsZ-0KiJw?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/minnesota/grand-rapids/grand-rapids.html', source: 'SkylineWebcams' },
  // ── New Jersey (3) ──
  { id: 'sky-us-atlantic-city-beach-2175', lat: 39.9327924, lng: -74.1800166, name: 'Atlantic City Beach', city: 'Atlantic City', country: 'US', stream_url: 'https://www.youtube.com/embed/vVyBOU9Huvo?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-jersey/atlantic-city/atlantic-city-beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-sea-isle-city-new-jersey-4266', lat: 39.1548404, lng: -74.6897791, name: 'Sea Isle City - New Jersey', city: 'Sea Isle City', country: 'US', stream_url: 'https://www.youtube.com/embed/FYOGiFH60uM?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-jersey/sea-isle-city/beach.html', source: 'SkylineWebcams' },
  { id: 'sky-us-wildwoods-4994', lat: 38.9821626, lng: -74.8217538, name: 'Wildwoods', city: 'Wildwood', country: 'US', stream_url: 'https://www.youtube.com/embed/cK71xhMRtds?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-jersey/wildwood/wildwoods.html', source: 'SkylineWebcams' },
  // ── New York (14) ──
  { id: 'sky-us-alexandria-bay-4473', lat: 44.3362411, lng: -75.9180626, name: 'Alexandria Bay', city: 'Alexandria Bay', country: 'US', stream_url: 'https://www.youtube.com/embed/H_EbNSqfoso?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/alexandria-bay/alexandria-bay.html', source: 'SkylineWebcams' },
  { id: 'sky-us-east-hampton-new-york-4916', lat: 40.9633868, lng: -72.1847598, name: 'East Hampton - New York', city: 'East Hampton', country: 'US', stream_url: 'https://www.youtube.com/embed/E8fp7TDgQUk?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/east-hampton/east-hampton.html', source: 'SkylineWebcams' },
  { id: 'sky-us-east-hampton-beach-4425', lat: 40.9440068, lng: -72.1908207, name: 'East Hampton Beach', city: 'New York', country: 'US', stream_url: 'https://www.youtube.com/embed/xM1-e429Y3A?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/east-hamptons.html', source: 'SkylineWebcams' },
  { id: 'sky-us-mirror-lake-new-york-2843', lat: 44.2904442, lng: -73.9819891, name: 'Mirror Lake - New York', city: 'Lake Placid', country: 'US', stream_url: 'https://www.youtube.com/embed/jB4Iwn2GJS4?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/lake-placid/mirror-lake.html', source: 'SkylineWebcams' },
  { id: 'sky-us-new-york-manhattan-545', lat: 40.8077507, lng: -73.9624901, name: 'New York - Manhattan', city: 'New York', country: 'US', stream_url: 'https://www.youtube.com/embed/X4P3JK-pIxo?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/new-york-manhattan.html', source: 'SkylineWebcams' },
  { id: 'sky-us-new-york-midtown-manhattan-4988', lat: 40.7526944, lng: -73.977253, name: 'New York - Midtown Manhattan', city: 'New York', country: 'US', stream_url: 'https://www.youtube.com/embed/H5W3Wox4zjQ?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/midtown-manhattan.html', source: 'SkylineWebcams' },
  { id: 'sky-us-new-york-city-harbor-2692', lat: 40.6352641, lng: -74.1599515, name: 'New York City Harbor', city: 'New York', country: 'US', stream_url: 'https://www.youtube.com/embed/l7b5RFAkKhY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/new-york-city-harbor.html', source: 'SkylineWebcams' },
  { id: 'sky-us-nyc-brooklyn-bridge-manhattan-2183', lat: 40.6956876, lng: -73.9878794, name: 'NYC Brooklyn Bridge - Manhattan', city: 'New York', country: 'US', stream_url: 'https://www.youtube.com/embed/1kvGNR_A3DY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/nyc-brooklyn-bridge-manhattan.html', source: 'SkylineWebcams' },
  { id: 'sky-us-old-forge-new-york-4132', lat: 43.7078965, lng: -74.9690857, name: 'Old Forge - New York', city: 'Old Forge', country: 'US', stream_url: 'https://www.youtube.com/embed/kGMOVb0IABs?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/old-forge/old-forge.html', source: 'SkylineWebcams' },
  { id: 'sky-us-port-henry-new-york-5042', lat: 44.0435221, lng: -73.4641078, name: 'Port Henry - New York', city: 'Port Henry', country: 'US', stream_url: 'https://www.youtube.com/embed/Bf7ewHyVP5I?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/port-henry/port-henry.html', source: 'SkylineWebcams' },
  { id: 'sky-us-sag-harbor-4426', lat: 40.9978727, lng: -72.2922292, name: 'Sag Harbor', city: 'New York', country: 'US', stream_url: 'https://www.youtube.com/embed/i3is63To-cE?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/sag-harbor.html', source: 'SkylineWebcams' },
  { id: 'sky-us-watertown-2185', lat: 43.9747838, lng: -75.9107565, name: 'Watertown', city: 'Watertown', country: 'US', stream_url: 'https://www.youtube.com/embed/gvJlnKJXJRY?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/watertown/watertown.html', source: 'SkylineWebcams' },
  { id: 'sky-us-whitesboro-new-york-4131', lat: 43.1218393, lng: -75.2911438, name: 'Whitesboro - New York', city: 'Whitesboro', country: 'US', stream_url: 'https://www.youtube.com/embed/KJ8C2vz7I70?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/whitesboro/whitesboro.html', source: 'SkylineWebcams' },
  { id: 'sky-us-world-trade-center-new-york-4910', lat: 40.7119004, lng: -74.012527, name: 'World Trade Center - New York', city: 'New York', country: 'US', stream_url: 'https://www.youtube.com/embed/5C9oM7C2Q9k?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/new-york/new-york/world-trade-center.html', source: 'SkylineWebcams' },
  // ── Oregon (3) ──
  { id: 'sky-us-ashland-oregon-2254', lat: 42.1885145, lng: -122.6904198, name: 'Ashland - Oregon', city: 'Ashland', country: 'US', stream_url: 'https://www.youtube.com/embed/OLrV_Hgl5Wo?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/oregon/ashland/ashland.html', source: 'SkylineWebcams' },
  { id: 'sky-us-lincoln-city-oregon-4951', lat: 44.9257956, lng: -124.0139314, name: 'Lincoln City - Oregon', city: 'Lincoln City', country: 'US', stream_url: 'https://www.youtube.com/embed/KFPYXo72qDI?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/oregon/lincoln-city/lincoln-city.html', source: 'SkylineWebcams' },
  { id: 'sky-us-seaside-beach-oregon-4892', lat: 45.9955902, lng: -123.9317946, name: 'Seaside Beach - Oregon', city: 'Seaside', country: 'US', stream_url: 'https://www.youtube.com/embed/Ce_vAKq1kUA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/oregon/seaside/beach.html', source: 'SkylineWebcams' },
  // ── Tennessee (2) ──
  { id: 'sky-us-downtown-of-nashville-4584', lat: 36.1698514, lng: -86.7868566, name: 'Downtown of Nashville', city: 'Nashville', country: 'US', stream_url: 'https://www.youtube.com/embed/ATbtGvbExP4?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/tennessee/nashville/downtown.html', source: 'SkylineWebcams' },
  { id: 'sky-us-jonesborough-tennessee-4213', lat: 36.2944397, lng: -82.4795787, name: 'Jonesborough - Tennessee', city: 'Jonesborough', country: 'US', stream_url: 'https://www.youtube.com/embed/PmXKd2Z_TVA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/tennessee/jonesborough/jonesborough.html', source: 'SkylineWebcams' },
  // ── Texas (8) ──
  { id: 'sky-us-aransas-pass-texas-3377', lat: 27.909666, lng: -97.1503865, name: 'Aransas Pass - Texas', city: 'Aransas Pass', country: 'US', stream_url: 'https://www.youtube.com/embed/Mn3vY8bordE?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/aransas-pass/harbor-park.html', source: 'SkylineWebcams' },
  { id: 'sky-us-conroe-texas-4335', lat: 30.3118769, lng: -95.4560512, name: 'Conroe - Texas', city: 'Conroe', country: 'US', stream_url: 'https://www.youtube.com/embed/UqrwUKSkMEE?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/conroe/lake.html', source: 'SkylineWebcams' },
  { id: 'sky-us-frisco-texas-4963', lat: 33.1505998, lng: -96.8238183, name: 'Frisco - Texas', city: 'Frisco', country: 'US', stream_url: 'https://www.youtube.com/embed/wCwrnWHzHyA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/frisco/frisco.html', source: 'SkylineWebcams' },
  { id: 'sky-us-galveston-texas-2288', lat: 29.3872254, lng: -94.992736, name: 'Galveston - Texas', city: 'Galveston', country: 'US', stream_url: 'https://www.youtube.com/embed/HkHhXsWci7Q?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/galveston/galveston.html', source: 'SkylineWebcams' },
  { id: 'sky-us-houston-downtown-texas-2287', lat: 29.7603205, lng: -95.3639963, name: 'Houston Downtown - Texas', city: 'Houston', country: 'US', stream_url: 'https://www.youtube.com/embed/wUQc3RoLAPs?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/houston/houston-downtown.html', source: 'SkylineWebcams' },
  { id: 'sky-us-nassau-bay-texas-3107', lat: 29.5446753, lng: -95.0910413, name: 'Nassau Bay - Texas', city: 'Nassau Bay', country: 'US', stream_url: 'https://www.youtube.com/embed/DwB8EQyWwig?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/nassau-bay/nassau-bay.html', source: 'SkylineWebcams' },
  { id: 'sky-us-south-padre-island-texas-2285', lat: 26.1036887, lng: -97.1646938, name: 'South Padre Island - Texas', city: 'South Padre Island', country: 'US', stream_url: 'https://www.youtube.com/embed/bvL_3W7F4Fk?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/south-padre-island/queen-isabella-causeway.html', source: 'SkylineWebcams' },
  { id: 'sky-us-south-padre-island-beach-texas-4138', lat: 26.20436, lng: -97.17731, name: 'South Padre Island Beach - Texas', city: 'South Padre Island', country: 'US', stream_url: 'https://www.youtube.com/embed/0FaRaPPTS8M?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/texas/south-padre-island/beach.html', source: 'SkylineWebcams' },
  // ── Wisconsin (8) ──
  { id: 'sky-us-eagle-river-wisconsin-4790', lat: 45.9219708, lng: -89.2566643, name: 'Eagle River - Wisconsin', city: 'Eagle River', country: 'US', stream_url: 'https://www.youtube.com/embed/d1KPGm1aWWE?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/eagle-river/eagle-river.html', source: 'SkylineWebcams' },
  { id: 'sky-us-ephraim-wisconsin-4610', lat: 45.1559164, lng: -87.1712517, name: 'Ephraim - Wisconsin', city: 'Ephraim', country: 'US', stream_url: 'https://www.youtube.com/embed/iKZtz27o6ns?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/ephraim/ephraim.html', source: 'SkylineWebcams' },
  { id: 'sky-us-greendale-broad-street-2822', lat: 42.9411813, lng: -87.9956363, name: 'Greendale - Broad Street', city: 'Greendale', country: 'US', stream_url: 'https://www.youtube.com/embed/ADsY4BQWZOU?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/greendale/broad-street.html', source: 'SkylineWebcams' },
  { id: 'sky-us-manitowoc-wisconsin-4476', lat: 44.0927599, lng: -87.6557269, name: 'Manitowoc - Wisconsin', city: 'Manitowoc', country: 'US', stream_url: 'https://www.youtube.com/embed/lty-_xS_xWA?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/manitowoc/marina.html', source: 'SkylineWebcams' },
  { id: 'sky-us-milwaukee-river-wisconsin-1889', lat: 43.4216109, lng: -88.0887561, name: 'Milwaukee River - Wisconsin', city: 'Milwaukee', country: 'US', stream_url: 'https://www.youtube.com/embed/JATo2lPJcaE?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/milwaukee/milwaukee-river.html', source: 'SkylineWebcams' },
  { id: 'sky-us-sturgeon-bay-wisconsin-3629', lat: 44.8385794, lng: -87.3626717, name: 'Sturgeon Bay - Wisconsin', city: 'Sturgeon Bay', country: 'US', stream_url: 'https://www.youtube.com/embed/bUomNllBJRU?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/sturgeon-bay/sturgeon-bay.html', source: 'SkylineWebcams' },
  { id: 'sky-us-superior-wisconsin-3506', lat: 46.7178779, lng: -92.0884228, name: 'Superior - Wisconsin', city: 'Superior', country: 'US', stream_url: 'https://www.youtube.com/embed/_L0u39B732I?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/superior/blatnik-bridge.html', source: 'SkylineWebcams' },
  { id: 'sky-us-washington-island-wisconsin-3381', lat: 45.3758358, lng: -86.899672, name: 'Washington Island - Wisconsin', city: 'Washington', country: 'US', stream_url: 'https://www.youtube.com/embed/UmiLYeh8-r8?autoplay=1&mute=1', stream_type: 'iframe', external_url: 'https://www.skylinewebcams.com/en/webcam/united-states/wisconsin/washington/washington-island-ferry-dock.html', source: 'SkylineWebcams' },
];

export async function fetchUsSkylineCameras(): Promise<CctvCamera[]> {
  return US_SKYLINE_CAMERAS;
}
