#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

say() {
  printf '%s\n' "$*"
}

ask() {
  local prompt="$1"
  local default_value="$2"
  local value
  if [[ -n "${default_value}" ]]; then
    read -r -p "${prompt} [${default_value}]: " value
    printf '%s' "${value:-${default_value}}"
  else
    read -r -p "${prompt}: " value
    printf '%s' "${value}"
  fi
}

confirm() {
  local prompt="$1"
  local default_value="${2:-n}"
  local suffix="[y/N]"
  [[ "${default_value}" == "y" ]] && suffix="[Y/n]"
  local answer
  read -r -p "${prompt} ${suffix}: " answer
  answer="${answer:-${default_value}}"
  [[ "${answer}" =~ ^[Yy]$ ]]
}

require_command() {
  command -v "$1" >/dev/null 2>&1
}

target_uid() {
  printf '%s' "${SUDO_UID:-$(id -u)}"
}

target_gid() {
  printf '%s' "${SUDO_GID:-$(id -g)}"
}

make_directory() {
  local path="$1"
  local mode="$2"
  if [[ "${EUID}" -eq 0 ]]; then
    install -d -m "${mode}" "${path}"
  elif require_command sudo; then
    sudo install -d -m "${mode}" "${path}"
  else
    install -d -m "${mode}" "${path}"
  fi
}

random_password() {
  if require_command openssl; then
    openssl rand -base64 36 | tr -d '\n'
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

write_env() {
  local osiris_port="$1"
  local db_name="$2"
  local db_user="$3"
  local db_password="$4"
  local db_host_path="$5"
  local archive_host_path="$6"
  local archive_container_path="$7"

  if [[ -f "${ENV_FILE}" ]]; then
    local backup="${ENV_FILE}.backup.$(date +%Y%m%d%H%M%S)"
    cp "${ENV_FILE}" "${backup}"
    say "Backed up existing .env to ${backup}"
  fi

  cat >"${ENV_FILE}" <<EOF
# Generated by scripts/osiris-install-wizard.sh
OSIRIS_PORT=${osiris_port}

POSTGRES_DB=${db_name}
POSTGRES_USER=${db_user}
POSTGRES_PASSWORD=${db_password}
POSTGRES_PORT=5432

WORLDSTATE_DB_DATA=${db_host_path}
RAW_ARCHIVE_HOST_PATH=${archive_host_path}
RAW_ARCHIVE_PATH=${archive_container_path}

EARTHQUAKE_DATA_MODE=database_with_live_fallback
EARTHQUAKE_DATABASE_MAX_AGE_MS=900000

COLLECTOR_SOURCE=usgs-earthquakes
COLLECT_INTERVAL_MS=300000
COLLECT_ON_STARTUP=1
MAX_FETCH_ATTEMPTS=3
MAX_RESPONSE_BYTES=26214400
REQUEST_TIMEOUT_MS=10000
RETRY_BASE_MS=500
STALE_RUN_AFTER_MS=900000

COLLECTOR_UID=$(target_uid)
COLLECTOR_GID=$(target_gid)
COLLECTOR_HEALTH_PORT=4001
COLLECTOR_LOG_LEVEL=info
EOF
}

prepare_directories() {
  local db_host_path="$1"
  local archive_host_path="$2"

  say "Preparing host directories:"
  say "  PostgreSQL: ${db_host_path}"
  say "  Raw archive: ${archive_host_path}"

  make_directory "${db_host_path}" "0750"
  make_directory "${archive_host_path}" "0750"

  if confirm "Set ownership of both directories to $(target_uid):$(target_gid) for this user?" "y"; then
    if [[ "${EUID}" -eq 0 ]]; then
      chown -R "$(target_uid):$(target_gid)" "${db_host_path}" "${archive_host_path}"
    elif require_command sudo; then
      sudo chown -R "$(target_uid):$(target_gid)" "${db_host_path}" "${archive_host_path}"
    else
      say "sudo is unavailable; leaving ownership unchanged."
    fi
  fi
}

show_disk_guidance() {
  say ""
  say "Disk setup guidance"
  say "-------------------"
  say "Use this if you want PostgreSQL and archives on a dedicated disk."
  say ""
  say "Preferred GUI path on Ubuntu Desktop:"
  say "  1. Open Disks."
  say "  2. Select the target disk."
  say "  3. Create/format a Linux filesystem such as ext4."
  say "  4. Mount it at a stable path, for example /mnt/osiris-worldstate."
  say "  5. Enable mount at startup in the mount options."
  say ""
  say "Ubuntu Server usually has no desktop GUI. In that case mount the disk"
  say "outside this wizard first, then give this wizard the mounted path."
  say ""
  if require_command lsblk; then
    say "Current block devices:"
    lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINTS,MODEL
  fi
  say ""
  say "This wizard does not format disks. That is intentionally separate because"
  say "formatting is destructive. Once the disk is mounted, the wizard prepares"
  say "the OSIRIS directories and writes Compose configuration."
}

check_docker() {
  if require_command docker && docker compose version >/dev/null 2>&1; then
    say "Docker Compose is available."
    return
  fi

  say "Docker Compose was not detected."
  if confirm "Install Docker packages with apt now?" "n"; then
    if ! require_command apt-get; then
      say "apt-get is unavailable; install Docker manually and rerun this wizard."
      exit 1
    fi
    if [[ "${EUID}" -eq 0 ]]; then
      apt-get update
      apt-get install -y docker.io docker-compose-plugin
      systemctl enable --now docker || true
    elif require_command sudo; then
      sudo apt-get update
      sudo apt-get install -y docker.io docker-compose-plugin
      sudo systemctl enable --now docker || true
    else
      say "sudo is unavailable; install Docker manually and rerun this wizard."
      exit 1
    fi
  fi
}

validate_compose() {
  say "Validating Compose configuration..."
  docker compose -f docker-compose.yml -f docker-compose.worldstate.yml config --quiet
}

main() {
  say "OSIRIS Ubuntu install wizard"
  say "============================"
  say "Repository: ${ROOT_DIR}"
  say ""

  if [[ -r /etc/os-release ]] && ! grep -qi '^ID=ubuntu' /etc/os-release; then
    say "Warning: this wizard is written for Ubuntu Server/Desktop. Continuing anyway."
  fi

  show_disk_guidance

  local data_root
  data_root="$(ask "Mounted disk/data root for OSIRIS state" "/srv/osiris-worldstate")"
  data_root="${data_root%/}"

  if [[ ! -d "${data_root}" ]]; then
    confirm "Create ${data_root} now?" "y" || exit 1
    make_directory "${data_root}" "0750"
  fi

  if ! findmnt -T "${data_root}" >/dev/null 2>&1; then
    say "Warning: ${data_root} is not on a detected mounted filesystem yet."
    confirm "Continue using this path anyway?" "n" || exit 1
  fi

  local db_host_path="${data_root}/postgres"
  local archive_host_path="${data_root}/archive"
  local archive_container_path="/archive"
  local osiris_port
  local db_name
  local db_user
  local db_password

  osiris_port="$(ask "OSIRIS web UI host port" "3000")"
  db_name="$(ask "PostgreSQL database name" "osiris_worldstate")"
  db_user="$(ask "PostgreSQL username" "osiris")"
  db_password="$(ask "PostgreSQL password" "$(random_password)")"

  prepare_directories "${db_host_path}" "${archive_host_path}"
  write_env "${osiris_port}" "${db_name}" "${db_user}" "${db_password}" "${db_host_path}" "${archive_host_path}" "${archive_container_path}"
  check_docker
  validate_compose

  say ""
  say "Wizard complete."
  say ""
  say "Start OSIRIS and world-state persistence with:"
  say "  docker compose -f docker-compose.yml -f docker-compose.worldstate.yml up -d osiris collector"
  say ""
  say "Verify state with:"
  say "  docker compose -f docker-compose.yml -f docker-compose.worldstate.yml ps"
  say "  docker compose -f docker-compose.yml -f docker-compose.worldstate.yml logs -f collector"
  say ""
  say "Database path: ${db_host_path}"
  say "Archive path:  ${archive_host_path}"
}

main "$@"
